This notebook explores and analyses my YouTube watch history using Python and pandas. It covers parsing raw Google Takeout data, cleaning and structuring watch records, and performing exploratory data analysis with a focus on music listening habits

# Parsing Watch History

## Initiating watch history retrieval

In [4]:
from enum import unique
from pathlib import Path
from bs4 import BeautifulSoup
from pandas.errors import CategoricalConversionWarning

project_root = Path.cwd().parent
watch_path = project_root / "data" / "raw" / "watch-history.html"

print(watch_path)
print(watch_path.exists())

C:\Users\MsnSi\PycharmProjects\Youtube_Music_Analysis\data\raw\watch-history.html
True

## Read data from watch history

Beautiful Soup is a Python library for parsing HTML/XML and turning it into something Python can navigate. Line 1 (htm) loads the html file into one string, and line 2 (soup) is used to parse through that string.

cards
│
├── cards[0] ── Watch history entry #1
├── cards[1] ── Watch history entry #2
├── cards[2] ── Watch history entry #3
├── cards[3] ── Watch history entry #4
└── ...

In [5]:
html = watch_path.read_text(encoding="utf-8")
soup = BeautifulSoup(html, "lxml")

cards = soup.select("div.outer-cell")

print(f"Number of activity records: {len(cards)}")

Number of activity records: 12200

## Grabbing the data from watch history

In [6]:
first_card = cards[0]
content = first_card.select_one("div.content-cell")

list(content.stripped_strings)

['Watched',
 'Mario Kart 8 Deluxe Players are Going Insane right now...',
 'Shortcat',
 '7 Sept 2026, 13:51:45 IST']

## Converting the Watched Video Data records into a dictionary data structure

In [7]:
parts = list(content.stripped_strings)
links = content.select("a")


record = {
    "action": parts[0],
    "title": parts[1],
    "channel": parts[2],
    "watched_at": parts[3],
    "video_url": links[0].get("href"),
}

print(record)

{'action': 'Watched', 'title': 'Mario Kart 8 Deluxe Players are Going Insane right now...', 'channel': 'Shortcat', 'watched_at': '7 Sept 2026, 13:51:45 IST', 'video_url': 'https://www.youtube.com/watch?v=TOKdln0vkrw'}

In [8]:
## Creating all the Records from Watch history

Create empty records list

FOR every card:
    Find the content inside this card

    Extract the strings
    Extract the links

    Build a dictionary

    Add dictionary to records

Finished → records now contains every watch-history entry

In [15]:
records = []
record_number = 0
bad_records = 0

for card in cards:
    content = card.select_one("div.content-cell")
    parts = list(content.stripped_strings)
    links = content.select("a")

    if len(parts) < 4:
        bad_records += 1
        print("PARTS:", parts)
        print("LINKS:", links)
        print("--------------------")
    else:
        record_number += 1

    #record = {
    #    "action": parts[0],
    #    "title": parts[1],
     #   "channel": parts[2],
      #  "watched_at": parts[3],
       # "video_url": links[0].get("href"),
    #}

    #records.append(record)
print("Number of normal records", record_number)
print("Number of bad records: ", bad_records)

PARTS: ['Watched', 'INH CARDS CUSTOMCARDS 3183db07 AIAvatar FaceUGC 9x16 18s A1 NA NL NL Nov2025 VO  1', '4 Sept 2026, 21:23:10 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=J5wkIKQfW_I">INH CARDS CUSTOMCARDS 3183db07 AIAvatar FaceUGC 9x16 18s A1 NA NL NL Nov2025 VO  1</a>]
--------------------
PARTS: ['Watched', 'INFNANO LIFESTYLE BUDGETING 698ef62a Ivelina2UGC UGC 9x16 NA A1 NA BG BG Jul2026 VO', '3 Sept 2026, 23:15:10 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=KkFMhhuYruM">INFNANO LIFESTYLE BUDGETING 698ef62a Ivelina2UGC UGC 9x16 NA A1 NA BG BG Jul2026 VO</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '1 Sept 2026, 03:39:29 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '31 Aug 2026, 14:24:55 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '29 Aug 2026, 22:38:37 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=4UCL50yWevo', '29 Aug 2026, 09:41:37 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=4UCL50yWevo">https://www.youtube.com/watch?v=4UCL50yWevo</a>]
--------------------
PARTS: ['Watched', 'Step into Candlelight, iconic music reimagined.', '29 Aug 2026, 03:40:32 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Oc9x0Gz99Hk">Step into Candlelight, iconic music reimagined.</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '29 Aug 2026, 03:31:34 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '29 Aug 2026, 03:31:34 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '29 Aug 2026, 03:18:49 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '28 Aug 2026, 17:42:44 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '28 Aug 2026, 00:14:13 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '27 Aug 2026, 23:30:33 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=mDTZgPkesGM', '24 Aug 2026, 19:16:00 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=mDTZgPkesGM">https://www.youtube.com/watch?v=mDTZgPkesGM</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '24 Aug 2026, 00:42:01 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '24 Aug 2026, 00:41:20 IST']
LINKS: []
--------------------
PARTS: ['Viewed a post that is no longer available', '24 Aug 2026, 00:14:17 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'Web限定動画_引越簡単手続き', '23 Aug 2026, 13:33:23 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=UJUWGb_e_BI">Web限定動画_引越簡単手続き</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '22 Aug 2026, 01:22:47 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=sbePPEBIZ-0', '21 Aug 2026, 05:41:00 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=sbePPEBIZ-0">https://www.youtube.com/watch?v=sbePPEBIZ-0</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=b_3DT2XY_ZY', '21 Aug 2026, 05:40:35 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=b_3DT2XY_ZY">https://www.youtube.com/watch?v=b_3DT2XY_ZY</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=d8AWJnW98ZQ', '21 Aug 2026, 05:40:05 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=d8AWJnW98ZQ">https://www.youtube.com/watch?v=d8AWJnW98ZQ</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=ycxLlQuNQUc', '21 Aug 2026, 05:36:29 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=ycxLlQuNQUc">https://www.youtube.com/watch?v=ycxLlQuNQUc</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=SuH_CzrwrQk', '21 Aug 2026, 05:35:57 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=SuH_CzrwrQk">https://www.youtube.com/watch?v=SuH_CzrwrQk</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=a79EAcCFY28', '21 Aug 2026, 05:35:35 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=a79EAcCFY28">https://www.youtube.com/watch?v=a79EAcCFY28</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=RZmZo6dPklw', '21 Aug 2026, 05:34:46 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=RZmZo6dPklw">https://www.youtube.com/watch?v=RZmZo6dPklw</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=h5Wrk2zO8xo', '21 Aug 2026, 05:33:46 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=h5Wrk2zO8xo">https://www.youtube.com/watch?v=h5Wrk2zO8xo</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=e_VZMoLxEno', '21 Aug 2026, 00:28:12 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=e_VZMoLxEno">https://www.youtube.com/watch?v=e_VZMoLxEno</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=Re52wlj5r5c', '21 Aug 2026, 00:17:17 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Re52wlj5r5c">https://www.youtube.com/watch?v=Re52wlj5r5c</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=bpe5zYiUW0U', '21 Aug 2026, 00:04:45 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=bpe5zYiUW0U">https://www.youtube.com/watch?v=bpe5zYiUW0U</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=Cz5b-K-kOUc', '19 Aug 2026, 21:54:05 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Cz5b-K-kOUc">https://www.youtube.com/watch?v=Cz5b-K-kOUc</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=vjthCSy0TC8', '19 Aug 2026, 17:02:44 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=vjthCSy0TC8">https://www.youtube.com/watch?v=vjthCSy0TC8</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=sbePPEBIZ-0', '19 Aug 2026, 16:07:20 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=sbePPEBIZ-0">https://www.youtube.com/watch?v=sbePPEBIZ-0</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=MBVJwO9S79k', '19 Aug 2026, 14:50:10 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=MBVJwO9S79k">https://www.youtube.com/watch?v=MBVJwO9S79k</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=a79EAcCFY28', '18 Aug 2026, 15:12:57 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=a79EAcCFY28">https://www.youtube.com/watch?v=a79EAcCFY28</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=MUlN09_F0zQ', '18 Aug 2026, 11:33:31 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=MUlN09_F0zQ">https://www.youtube.com/watch?v=MUlN09_F0zQ</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=d8AWJnW98ZQ', '18 Aug 2026, 11:32:44 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=d8AWJnW98ZQ">https://www.youtube.com/watch?v=d8AWJnW98ZQ</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=6TyaSBrYCEE', '17 Aug 2026, 12:57:58 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=6TyaSBrYCEE">https://www.youtube.com/watch?v=6TyaSBrYCEE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=5NGVgcPEZ9E', '17 Aug 2026, 12:35:46 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=5NGVgcPEZ9E">https://www.youtube.com/watch?v=5NGVgcPEZ9E</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=d8AWJnW98ZQ', '16 Aug 2026, 19:30:15 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=d8AWJnW98ZQ">https://www.youtube.com/watch?v=d8AWJnW98ZQ</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=ISeGnpDKW5s', '16 Aug 2026, 03:34:18 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=ISeGnpDKW5s">https://www.youtube.com/watch?v=ISeGnpDKW5s</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=K_xVeA-svlE', '14 Aug 2026, 23:35:46 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=K_xVeA-svlE">https://www.youtube.com/watch?v=K_xVeA-svlE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=RZmZo6dPklw', '14 Aug 2026, 15:45:23 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=RZmZo6dPklw">https://www.youtube.com/watch?v=RZmZo6dPklw</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=KBGS61iDVdg', '13 Aug 2026, 23:30:06 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=KBGS61iDVdg">https://www.youtube.com/watch?v=KBGS61iDVdg</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=Fb5eV_6cY4o', '12 Aug 2026, 13:07:37 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Fb5eV_6cY4o">https://www.youtube.com/watch?v=Fb5eV_6cY4o</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=Z62gLSMOf1E', '11 Aug 2026, 19:39:49 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Z62gLSMOf1E">https://www.youtube.com/watch?v=Z62gLSMOf1E</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=X8FEnQKX_WA', '7 Aug 2026, 08:36:54 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=X8FEnQKX_WA">https://www.youtube.com/watch?v=X8FEnQKX_WA</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=iIlVmjpReEQ', '7 Aug 2026, 07:07:35 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=iIlVmjpReEQ">https://www.youtube.com/watch?v=iIlVmjpReEQ</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '6 Aug 2026, 23:28:26 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=Kp23TqdC6rU', '5 Aug 2026, 04:09:39 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Kp23TqdC6rU">https://www.youtube.com/watch?v=Kp23TqdC6rU</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=l1G5vLogZgE', '3 Aug 2026, 22:21:27 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=l1G5vLogZgE">https://www.youtube.com/watch?v=l1G5vLogZgE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=f2tI_mFl58c', '3 Aug 2026, 20:06:29 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=f2tI_mFl58c">https://www.youtube.com/watch?v=f2tI_mFl58c</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '3 Aug 2026, 14:08:57 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=4e7-Dj7uuhg', '3 Aug 2026, 01:22:33 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=4e7-Dj7uuhg">https://www.youtube.com/watch?v=4e7-Dj7uuhg</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=PHwuReQdXkw', '2 Aug 2026, 17:41:09 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=PHwuReQdXkw">https://www.youtube.com/watch?v=PHwuReQdXkw</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=awbpXHEDEmo', '2 Aug 2026, 07:58:37 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=awbpXHEDEmo">https://www.youtube.com/watch?v=awbpXHEDEmo</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '1 Aug 2026, 10:38:43 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=w2P3f4eoIdE', '1 Aug 2026, 05:07:18 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=w2P3f4eoIdE">https://www.youtube.com/watch?v=w2P3f4eoIdE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=2xHlmqaisRE', '30 Jul 2026, 16:15:28 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=2xHlmqaisRE">https://www.youtube.com/watch?v=2xHlmqaisRE</a>]
--------------------
PARTS: ['Watched', 'Shortened: 【V5068角色轮播图B森之国-杖剑传说-EN-刘子齐-赵健-9x16-0325】', '30 Jul 2026, 15:31:38 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=nK13114mB24">Shortened: 【V5068角色轮播图B森之国-杖剑传说-EN-刘子齐-赵健-9x16-0325】</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=SuH_CzrwrQk', '30 Jul 2026, 04:02:50 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=SuH_CzrwrQk">https://www.youtube.com/watch?v=SuH_CzrwrQk</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=lyQ5GLGHxjE', '29 Jul 2026, 17:18:00 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=lyQ5GLGHxjE">https://www.youtube.com/watch?v=lyQ5GLGHxjE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=d-tFAjOfRrE', '29 Jul 2026, 17:12:55 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=d-tFAjOfRrE">https://www.youtube.com/watch?v=d-tFAjOfRrE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=wIqbBRNl5EI', '28 Jul 2026, 21:56:21 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=wIqbBRNl5EI">https://www.youtube.com/watch?v=wIqbBRNl5EI</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '28 Jul 2026, 19:32:59 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=PDejO25i4dw', '28 Jul 2026, 11:25:11 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=PDejO25i4dw">https://www.youtube.com/watch?v=PDejO25i4dw</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=43a1J6erR5w', '28 Jul 2026, 11:05:23 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=43a1J6erR5w">https://www.youtube.com/watch?v=43a1J6erR5w</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=p53x5X-4lZ4', '28 Jul 2026, 03:30:41 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=p53x5X-4lZ4">https://www.youtube.com/watch?v=p53x5X-4lZ4</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '27 Jul 2026, 04:35:57 IST']
LINKS: []
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=6AUpyTniPQA', '26 Jul 2026, 23:25:03 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=6AUpyTniPQA">https://www.youtube.com/watch?v=6AUpyTniPQA</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=aD3u-gVhPUc', '26 Jul 2026, 23:24:52 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=aD3u-gVhPUc">https://www.youtube.com/watch?v=aD3u-gVhPUc</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=oJ259K05Q3E', '26 Jul 2026, 23:24:20 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=oJ259K05Q3E">https://www.youtube.com/watch?v=oJ259K05Q3E</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=DlNHAJf6l3M', '26 Jul 2026, 22:13:51 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=DlNHAJf6l3M">https://www.youtube.com/watch?v=DlNHAJf6l3M</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=WuNokvOy2l0', '26 Jul 2026, 20:39:08 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=WuNokvOy2l0">https://www.youtube.com/watch?v=WuNokvOy2l0</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=6aCBAxVTHyc', '26 Jul 2026, 01:42:22 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=6aCBAxVTHyc">https://www.youtube.com/watch?v=6aCBAxVTHyc</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=tkYySAvRKko', '25 Jul 2026, 20:30:38 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=tkYySAvRKko">https://www.youtube.com/watch?v=tkYySAvRKko</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=LgrKrFSq9L0', '25 Jul 2026, 04:53:34 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=LgrKrFSq9L0">https://www.youtube.com/watch?v=LgrKrFSq9L0</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=mSfUScoS9-U', '24 Jul 2026, 03:59:01 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=mSfUScoS9-U">https://www.youtube.com/watch?v=mSfUScoS9-U</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=EoUp1btZZPg', '23 Jul 2026, 02:32:24 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=EoUp1btZZPg">https://www.youtube.com/watch?v=EoUp1btZZPg</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=im2FiepxJrs', '23 Jul 2026, 02:32:22 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=im2FiepxJrs">https://www.youtube.com/watch?v=im2FiepxJrs</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=htSp5nhAEpw', '23 Jul 2026, 02:32:15 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=htSp5nhAEpw">https://www.youtube.com/watch?v=htSp5nhAEpw</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=utTPHR7Q8yE', '23 Jul 2026, 02:32:11 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=utTPHR7Q8yE">https://www.youtube.com/watch?v=utTPHR7Q8yE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=MvArvN1sJWg', '23 Jul 2026, 02:32:00 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=MvArvN1sJWg">https://www.youtube.com/watch?v=MvArvN1sJWg</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=ib_Ji0vWSJA', '23 Jul 2026, 02:31:27 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=ib_Ji0vWSJA">https://www.youtube.com/watch?v=ib_Ji0vWSJA</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=xRMKrKp6efU', '23 Jul 2026, 02:31:14 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=xRMKrKp6efU">https://www.youtube.com/watch?v=xRMKrKp6efU</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=C6HeF-05k6s', '23 Jul 2026, 02:31:11 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=C6HeF-05k6s">https://www.youtube.com/watch?v=C6HeF-05k6s</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=6USGfFJJ-Uo', '23 Jul 2026, 02:31:08 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=6USGfFJJ-Uo">https://www.youtube.com/watch?v=6USGfFJJ-Uo</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=dpcb9YLgjnc', '23 Jul 2026, 02:30:36 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=dpcb9YLgjnc">https://www.youtube.com/watch?v=dpcb9YLgjnc</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=cLEdxZx4e7s', '23 Jul 2026, 02:30:04 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=cLEdxZx4e7s">https://www.youtube.com/watch?v=cLEdxZx4e7s</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=ssigKAP-iJI', '23 Jul 2026, 02:29:45 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=ssigKAP-iJI">https://www.youtube.com/watch?v=ssigKAP-iJI</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=LeCyXC0VzlI', '23 Jul 2026, 02:29:33 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=LeCyXC0VzlI">https://www.youtube.com/watch?v=LeCyXC0VzlI</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=5RUhDCW_C2Y', '23 Jul 2026, 02:29:28 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=5RUhDCW_C2Y">https://www.youtube.com/watch?v=5RUhDCW_C2Y</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=Ab9g9s6Gvrw', '23 Jul 2026, 02:29:12 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=Ab9g9s6Gvrw">https://www.youtube.com/watch?v=Ab9g9s6Gvrw</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=2GA1d7ZmlGE', '23 Jul 2026, 02:29:03 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=2GA1d7ZmlGE">https://www.youtube.com/watch?v=2GA1d7ZmlGE</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=WU88VhYGx5Q', '23 Jul 2026, 02:06:29 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=WU88VhYGx5Q">https://www.youtube.com/watch?v=WU88VhYGx5Q</a>]
--------------------
PARTS: ['Watched', 'https://www.youtube.com/watch?v=-PTlvzWO6Eo', '23 Jul 2026, 00:48:07 IST']
LINKS: [<a href="https://www.youtube.com/watch?v=-PTlvzWO6Eo">https://www.youtube.com/watch?v=-PTlvzWO6Eo</a>]
--------------------
PARTS: ['Viewed a post that is no longer available', '22 Jul 2026, 01:56:05 IST']
LINKS: []
--------------------

It seems like our parser is a bit flawed due to some bad data within the watch history, there seems to be 4 types of outliers:

1. Ads: 3 Parts, but no obvious link
2. Community Posts: 3 parts, no link
3. Unlisted Videos: 3 Parts, Link exists in the *links* field
4. Privated Videos: 3 Parts, 1 Link in parts, 2 links in *links field

## Updated Record Retrieval

In [40]:
records = []
record_number = 0
missing_channel_records = 0
non_video_records = 0

zero_links = 0
one_link = 0
two_or_more_links = 0


for card in cards:
    content = card.select_one("div.content-cell")
    parts = list(content.stripped_strings)
    links = content.select("a")

    if parts[0] != 'Watched':
        non_video_records += 1
        continue

    if len(parts) == 4:
        record_number += 1
        record = {
            "action": parts[0],
            "title": parts[1],
            "channel": parts[2],
            "watched_at": parts[3],
            "video_url": links[0].get("href"),
        }

    elif len(parts) == 3:
        missing_channel_records += 1

        if len(links) <= 0:
            zero_links += 1
        elif len(links) == 1:
            one_link += 1
        elif len(links) == 2:
            two_or_more_links += 1

        record = {
            "action": parts[0],
            "title": parts[1],
            "channel": None,
            "watched_at": parts[2],
            "video_url": links[0].get("href"),
        }


    records.append(record)

print("Number of normal records", record_number)
print("Number of records with missing channels: ", missing_channel_records)
print("Number of non-video records: ", non_video_records)

print("Number of bad records with zero links: ", zero_links)
print("Number of records with one link: ", one_link)
print("Number of records with two or more links: ", two_or_more_links)

Number of normal records 9945
Number of records with missing channels:  115
Number of non-video records:  2140
Number of bad records with zero links:  0
Number of records with one link:  115
Number of records with two or more links:  0

In [41]:
zero_links = 0
one_link = 0
two_or_more_links = 0

# Using Pandas

## Implementing the Pandas Library

In [42]:
import pandas as pd

records_dataframe = pd.DataFrame(records)

records_dataframe.head()

,action,title,channel,watched_at,video_url
0,Watched,Mario Kart 8 Deluxe Players are Going Insane r...,Shortcat,"7 Sept 2026, 13:51:45 IST",https://www.youtube.com/watch?v=TOKdln0vkrw
1,Watched,Oops! Nintendo reveals Mario Kart 8's DEBUG mode,Beta64,"7 Sept 2026, 13:50:46 IST",https://www.youtube.com/watch?v=Lg1QI8ZkPRU
2,Watched,I Love These Uma Musume,Starfang,"7 Sept 2026, 13:44:34 IST",https://www.youtube.com/watch?v=5OOE4WORb5Q
3,Watched,第三方居然出了MG飛昇自由？大砲還有拉伸結構，還可以全彈髮射！ #gundam #갓건담 #...,玩具測評總動員,"7 Sept 2026, 13:43:43 IST",https://www.youtube.com/watch?v=R9922GyZmvw
4,Watched,【#なつめぇ誕生日2026】🎂ケーキ食べようよ！【来栖夏芽/にじさんじ】,来栖 夏芽-kurusu natsume-【にじさんじ】,"7 Sept 2026, 13:35:14 IST",https://www.youtube.com/watch?v=Ftji2LKqVXs

## Exploring the properties of the DataFrame

We can use the shape attribute to understand the general structure of the DataFrame

In [43]:
records_dataframe.shape

(10060, 5)

in the below code, we get (100060,5) which likely represents the number of row entries and the number of coloumn entries in our DataFrame

The dtypes attribute is used to expose the types of each column entry in the dataFrame

In [44]:
records_dataframe.dtypes

action        str
title         str
channel       str
watched_at    str
video_url     str
dtype: object

Before changing the data, We already know there should be at least 115 missing channel values from our parsing work, we need to figure out what's missing from those entries.

We can use the isna() function, which will scan through each cell in the Data Frame and check if a value exists, combine this with .sum() to add the up these entries together to see how many of each value is missing.

Previously both channel and video_url had shown 115 entries, this was a mistake as a result of a flawed parser which failed to catch the fact that I failed to realise that just because an entry might have less parts (due to not having a channel), we could still grab their link as that was from another array from the content entry

In [46]:
records_dataframe.isna().sum()

action          0
title           0
channel       115
watched_at      0
video_url       0
dtype: int64

# Initial Data Cleaning

We need to clean up the data so we can use it for analysis, firstly we'll convert the "watched_at" field into a timestamp so it can be used later for analysis

## Getting Rid of Bad Entries

Getting Rid of Bad Entries

In [90]:
valid_channel_records = records_dataframe[records_dataframe["channel"].notna()]

records_dataframe = valid_channel_records


#print(records_dataframe.shape)
#records_dataframe.head()


records_dataframe.reset_index(drop = True)

,action,title,channel,watched_at,video_url
0,Watched,Mario Kart 8 Deluxe Players are Going Insane r...,Shortcat,2026-09-07 13:51:45,https://www.youtube.com/watch?v=TOKdln0vkrw
1,Watched,Oops! Nintendo reveals Mario Kart 8's DEBUG mode,Beta64,2026-09-07 13:50:46,https://www.youtube.com/watch?v=Lg1QI8ZkPRU
2,Watched,I Love These Uma Musume,Starfang,2026-09-07 13:44:34,https://www.youtube.com/watch?v=5OOE4WORb5Q
3,Watched,第三方居然出了MG飛昇自由？大砲還有拉伸結構，還可以全彈髮射！ #gundam #갓건담 #...,玩具測評總動員,2026-09-07 13:43:43,https://www.youtube.com/watch?v=R9922GyZmvw
4,Watched,【#なつめぇ誕生日2026】🎂ケーキ食べようよ！【来栖夏芽/にじさんじ】,来栖 夏芽-kurusu natsume-【にじさんじ】,2026-09-07 13:35:14,https://www.youtube.com/watch?v=Ftji2LKqVXs
...,...,...,...,...,...
9940,Watched,Wonder Acute (Onsen) #ウマ娘 #umamusume #anime #...,Kidd Thunder 76,2026-07-07 17:56:08,https://www.youtube.com/watch?v=fbnlwV1jmdE
9941,Watched,I NEVER lost faith in YukaF,NiceWigg,2026-07-07 17:54:06,https://www.youtube.com/watch?v=BcbTEjpaY5M
9942,Watched,Haru Breaks The Fourth Wall #voiceacting#voice...,hapyr,2026-07-07 17:54:00,https://www.youtube.com/watch?v=qXvvSKL0hgA
9943,Watched,An Agnes Digital Interaction #animecharacter#a...,hapyr,2026-07-07 17:53:34,https://www.youtube.com/watch?v=wUfEL06bVSM
9944,Watched,Fufu Being Helpful.. I think.. #memes#anime#he...,hapyr,2026-07-07 17:52:52,https://www.youtube.com/watch?v=CmyTcRLnKT8

We can use the .str attribute to access all the strings in a specific row entry, and then we can use [n:n] to slice off a specific section of the string. In this context, we slice off the timezone so we can more easily convert our entry times that are currently strings into timestamp data types

In [92]:
#converted_watched_at_entries = pd.to_datetime(records_dataframe["watched_at"].str[:-4], dayfirst=True)

#records_dataframe["watched_at"] = converted_watched_at_entries

records_dataframe.head()

,action,title,channel,watched_at,video_url
0,Watched,Mario Kart 8 Deluxe Players are Going Insane r...,Shortcat,2026-09-07 13:51:45,https://www.youtube.com/watch?v=TOKdln0vkrw
1,Watched,Oops! Nintendo reveals Mario Kart 8's DEBUG mode,Beta64,2026-09-07 13:50:46,https://www.youtube.com/watch?v=Lg1QI8ZkPRU
2,Watched,I Love These Uma Musume,Starfang,2026-09-07 13:44:34,https://www.youtube.com/watch?v=5OOE4WORb5Q
3,Watched,第三方居然出了MG飛昇自由？大砲還有拉伸結構，還可以全彈髮射！ #gundam #갓건담 #...,玩具測評總動員,2026-09-07 13:43:43,https://www.youtube.com/watch?v=R9922GyZmvw
4,Watched,【#なつめぇ誕生日2026】🎂ケーキ食べようよ！【来栖夏芽/にじさんじ】,来栖 夏芽-kurusu natsume-【にじさんじ】,2026-09-07 13:35:14,https://www.youtube.com/watch?v=Ftji2LKqVXs

## Determining what is a music video or not

There are a few methods we could use to track whether a video is music related or not.
- Keeping track of a channel that is music-focused and checking if a video comes from that channel (also works for topic channels
- Checking the title of the video for certain keywords
- Using playlist data, if a video appears in a playlist, then it should be included
- Checking the metadata from the URL, either from the Takeout data or Youtube's own metadata

To do that though, we'll need to extend our DataFrame furhter to be able to include video ID as a metric for comparison

In [99]:
video_ids = records_dataframe["video_url"].str.split("v=").str[1]

video_ids.str.len().unique() #Checking that all video ids equally return 11 characters

records_dataframe["video_ids"] = video_ids

records_dataframe.head()
#records_dataframe.shape

,action,title,channel,watched_at,video_url,video_ids
0,Watched,Mario Kart 8 Deluxe Players are Going Insane r...,Shortcat,2026-09-07 13:51:45,https://www.youtube.com/watch?v=TOKdln0vkrw,TOKdln0vkrw
1,Watched,Oops! Nintendo reveals Mario Kart 8's DEBUG mode,Beta64,2026-09-07 13:50:46,https://www.youtube.com/watch?v=Lg1QI8ZkPRU,Lg1QI8ZkPRU
2,Watched,I Love These Uma Musume,Starfang,2026-09-07 13:44:34,https://www.youtube.com/watch?v=5OOE4WORb5Q,5OOE4WORb5Q
3,Watched,第三方居然出了MG飛昇自由？大砲還有拉伸結構，還可以全彈髮射！ #gundam #갓건담 #...,玩具測評總動員,2026-09-07 13:43:43,https://www.youtube.com/watch?v=R9922GyZmvw,R9922GyZmvw
4,Watched,【#なつめぇ誕生日2026】🎂ケーキ食べようよ！【来栖夏芽/にじさんじ】,来栖 夏芽-kurusu natsume-【にじさんじ】,2026-09-07 13:35:14,https://www.youtube.com/watch?v=Ftji2LKqVXs,Ftji2LKqVXs

### Reading CSV Files for Video IDs

Now we want to try converting the CSV files from the music and playlist folders from the google takeout data to act as our first basis for finding music videos.

In [100]:
music_library_csv_path = project_root / "data" / "raw" / "music library songs.csv"

music_library_dataframe = pd.read_csv(music_library_csv_path)

In [101]:
music_library_dataframe.head()

,Video ID,Song Title,Album Title,Artist Name 1,Artist Name 2
0,1aTIvok5__w,Across the Galaxies,Deep Sleep Relaxation Music,Mrm Team,NaN
1,B2i_23Ufnj0,aLIEz [mZk ver.] - aLIEz (mZk Version),&Z,SawanoHiroyuki[nZk],mizuki
2,tQRk5OFsGXo,Andromeda,Still Still Stellar,星街すいせい,NaN
3,UxG0N1Nfoq0,朝です… - Asadesu,Seishunbutayarouha Bunny Girl Senpaino Yumeomi...,fox capture plan,NaN
4,fFB88ikHOGI,Aurora: Delta Waves 2.5 Hz,"Brain Waves Music, Vol. 1 - Delta Waves",Mrm team,NaN

Now that we have a 2nd dataframe, we can start checking if there are songs in our watch history that are listed within some of our music libraries

In [102]:
library_matches = music_library_dataframe["Video ID"].isin(records_dataframe["video_ids"])

library_matches.sum()

np.int64(2)

So it seems like there are 2 instances of music in the library that were in my watch history.

While i think that this method is interesting, I'm unsure how useful it could be, at least for this specific instance of my Google takeout as it is very small and relatively recent (only going back to the 7th of July this year), which would mean cross-referencing video ids to playlists would be relatively pointless given that I've mostly switched to usingYyoutube's auto generated playlists, and that I also don't listen to those songs as often (if at all) anymore. in my opinion, I think it would be a better idea to use some of our other methods.

# Using Youtube's Data API

## Basics of receiving requests

Firstly, we want to import our Youtube API Key

In [103]:
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("YOUTUBE_API_KEY")
print(api_key is not None)

True

Now let's make an API request using our DataFrame

In [136]:
#records_dataframe.head(170)

music_video_id = records_dataframe.loc[168, "video_ids"]
music_video_title = records_dataframe.loc[168,"title"]

non_music_video_id = records_dataframe.loc[26, "video_ids"]
non_music_video_title = records_dataframe.loc[26, "title"]

print(f'The video: {music_video_title}, has the video id: {music_video_id}')
print(f'The non music video: {non_music_video_title}, has the video id: {non_music_video_id}')

The video: Why Do I (with Hatsune Miku), has the video id: HMFNXgu7L3Q
The non music video: MAFIA 3 DEFINITIVE EDITION All Cutscenes (Full Game Movie) 4K Ultra HD, has the video id: qNdhM8j7scU

In [137]:
import requests

url = "https://www.googleapis.com/youtube/v3/videos"

params = {
    "part": "snippet,contentDetails",
    "id": music_video_id,
    "key": api_key
}

non_music_video_params = {
    "part": "snippet,contentDetails",
    "id": non_music_video_id,
    "key": api_key
}

music_video_response = requests.get(url, params=params)
non_music_video_response = requests.get(url, params=non_music_video_params)

music_video_data = music_video_response.json()
non_music_video_data = non_music_video_response.json()
#print(data)

In [138]:
mv_item = music_video_data["items"][0]
nmv_item = non_music_video_data["items"][0]

print(mv_item.keys())
print(mv_item["snippet"].keys())
print(mv_item["contentDetails"].keys())

dict_keys(['kind', 'etag', 'id', 'snippet', 'contentDetails'])
dict_keys(['publishedAt', 'channelId', 'title', 'description', 'thumbnails', 'channelTitle', 'tags', 'categoryId', 'liveBroadcastContent', 'defaultLanguage', 'localized', 'defaultAudioLanguage'])
dict_keys(['duration', 'dimension', 'definition', 'caption', 'licensedContent', 'regionRestriction', 'contentRating', 'projection'])

In [139]:
mv_snippet = mv_item["snippet"]
mv_content = mv_item["contentDetails"]

print("Title:", mv_snippet["title"])
print("Channel:", mv_snippet["channelTitle"])
print("Category:", mv_snippet["categoryId"])
print("Duration:", mv_content["duration"])
print("Tags:", mv_snippet.get("tags", []))

print("")
nmv_snippet = nmv_item["snippet"]
nmv_content = nmv_item["contentDetails"]

print("Title:", nmv_snippet["title"])
print("Channel:", nmv_snippet["channelTitle"])
print("Category:", nmv_snippet["categoryId"])
print("Duration:", nmv_content["duration"])
print("Tags:", nmv_snippet.get("tags", []))

Title: Why Do I (with Hatsune Miku)
Channel: Set It Off
Category: 10
Duration: PT2M36S
Tags: ['set it off', 'upside down', 'cody carson', 'maxx danziger', 'zach dewall', 'dan clermont', 'life afraid', 'hypnotized', 'wolf in sheeps clothing', "wolf in sheep's clothing", 'Duality', 'BAND VLOG', 'BAND VLOGS', 'why worry', 'bleak December', 'ancient history', 'Forever stuck in our youth', 'SIO', '21 Pilots', 'Twenty one Pilots', 'panic at the disco', 'brendon urie', 'top', 'Joshdun', 'MCR', 'My chemical romance', 'pete wentz', 'Fan girl', 'Set it off band', 'All time Low', 'night core', 'nightcore']

Title: MAFIA 3 DEFINITIVE EDITION All Cutscenes (Full Game Movie) 4K Ultra HD
Channel: Gamer's Little Playground
Category: 20
Duration: PT6H3M40S
Tags: ['game', 'full', 'gameplay', 'no commentary', 'full gameplay', 'MAFIA 3 DEFINITIVE EDITION All Cutscenes (Full Game Movie) 4K Ultra HD', 'mafia 3 full game', 'full gameplay walkthrough', 'mafia 3 definitive edition', 'mafia 3', 'mafia 3 all cutscenes', 'mafia 3 walkthrough', 'mafia 3 gameplay', 'mafia 3 movie', 'joe barbaro', 'mafia definitive edition', 'mafia 3 definitive edition all cutscenes', 'mafia 3 4k 60fps', 'mafia 3 definitive edition full game', 'mafia 3 walkthrough part 1', 'tommy angelo', 'mafia 3 ending']

## Finding the nuances between "music videos"

We now need to find an example of videos that may be considered on the cusp of being a music video

- a music video uploaded by a non-official channel: Umamusume] yume wo kakeru! (Canopus Ver) (Lyrics/Color Coded) [TV Anime 2nd season https://www.youtube.com/watch?v=OpbokSpFAPk&list=RDOpbokSpFAPk&start_radio=1
- a cover/remix/nightcore song: IE 奏 - スキマスイッチ (Cover) / VESPERBELL ヨミ
https://www.youtube.com/watch?v=-BYdGfsSrHA&list=RD-BYdGfsSrHA&start_radio=1
- a live performance : Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ] - https://www.youtube.com/watch?v=2zh66iI3fVc&list=RD2zh66iI3fVc&start_radio=1
- a normal ~3–5 minute non-music video; Gus Fring's Astronomical Offer : https://www.youtube.com/watch?v=ThZMClhU35I&t=1s
- a very long music mix/album - [1 Hour] Yorushika ヨルシカ songs collection / playlist https://www.youtube.com/watch?v=nOeWWduMb9Q&list=RDnOeWWduMb9Q&start_radio=1
- a video that contains music but that you personally wouldn't consider a music listen: Popular Songs That Were Later Used in Anime - https://www.youtube.com/watch?v=by2Dx-_souY

In [140]:
non_official_music = "OpbokSpFAPk"
cover = "-BYdGfsSrHA"
live_performance = "2zh66iI3fVc"
short_non_music = "ThZMClhU35I"
long_music = "nOeWWduMb9Q"
contains_music = "by2Dx-_souY"

test_video_ids = [ non_official_music, cover, live_performance, short_non_music, long_music, contains_music ]

combined_video_ids = ",".join(test_video_ids)

test_params = {
    "part": "snippet,contentDetails",
    "id": combined_video_ids,
    "key": api_key
}

test_response = requests.get(url, params=test_params)
test_data = test_response.json()

for item in test_data["items"]:
    test_snippet = item["snippet"]
    test_content = item["contentDetails"]

    print("Title:", test_snippet["title"])
    print("Channel:", test_snippet["channelTitle"])
    print("Category:", test_snippet["categoryId"])
    print("Duration:", test_content["duration"])
    print("Tags:", test_snippet.get("tags", []))
    print("")

Title: 【ウマ娘】ユメヲカケル! (カノープスVer) (パート分け/Color Coded/Lyrics)【Run for Our Dream】
Channel: 🐈Kogane Music
Category: 10
Duration: PT4M52S
Tags: ['ウマ娘', 'パート分け', 'ユメヲカケル!', '賽馬娘', 'yumewokakeru', 'yume wo kakeru', '讓夢想成真吧', '让梦想成真吧', 'パート割', '歌割り', 'lyrics', 'kogane music', 'フル', 'full', '우마무스메']

Title: 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Channel: VESPERBELL_YM
Category: 10
Duration: PT5M30S
Tags: ['VESPERBELL', '歌ってみた', 'カバー', 'cover', 'VTuber', 'バーチャルYouTuber', 'ヴェスパーベル', 'YOMI', 'KASUKA', 'ヨミ', 'カスカ', 'Vsinger']

Title: Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ]
Channel: Yudha - ユダ
Category: 10
Duration: PT4M34S
Tags: ['Nijisanji', 'Vtuber', 'Virtual Youtuber', 'Vtuber ENG', 'Nijisanji ENG', 'Hololive', 'Inui Toko', 'Hoshimachi Suisei', 'Inui', 'Suisei', 'Inui Eng', 'Suisei Eng', 'Hana ni Bourei']

Title: Gus Fring's Astronomical Offer | No Más | Breaking Bad
Channel: Breaking Bad & Better Call Saul
Category: 1
Duration: PT3M23S
Tags: ['Breaking Bad', 'Breaking Bad Season 3', 'Breaking Bad Season 3 Episode 1', 'No Mas', 'Walter White', 'Gus Fring', 'Bryan Cranston', 'Giancarlo Esposito', 'Three million dollars for three months of your time', 'I am not a criminal', 'Los Pollos Hermanos', 'superlab offer', 'Gus Fring offer', 'Walt meets Gus', 'breaking bad clips', 'walter white heisenberg', 'chicken brother', 'crime drama', 'breaking bad iconic scenes', 'los pollos hermanos meeting', 'breaking bad season 3 clips', 'walter white negotiation', 'amc', 'sony']

Title: [1 Hour] Yorushika ヨルシカ songs collection / playlist
Channel: NorthGround
Category: 10
Duration: PT1H12M58S
Tags: ['yorushika live', 'yorushika itte', 'yorushika guitar', 'yorushika cover', 'yorushika piano', 'yorushika reaction', 'yorushika 噓月', 'yorushika 介紹', 'yorushika album', 'yorushika amy', 'yorushika ano natsu', 'yorushika ame to cappuccino', 'yorushika aruku', 'yorushika acoustic guitar cover', 'yorushika august a certain person moonlight', 'yorushika amy lyrics', 'yorushika bass', 'yorushika band cover', 'yorushika bass cover', 'yorushika bomber', 'yorushika bass tab', 'yorushika bgm', 'yorushika best']

Title: Popular Songs That Were Later Used in Anime
Channel: Kuma
Category: 24
Duration: PT5M
Tags: ['Popular songs', 'most popular anime song', 'famous songs', 'Kuma', 'Anime songs', 'anime opening']

Interesting to see is that the ones that I would've considered music were also agreed to be by Youtube's metadata, and the ones that weren't like the non music video was not, interestingly, Youtube was agreed with my own opinion about the last 2 videos, the music compilation was considered a music video (which by in large I would mostly agree with) and the popular songs video which definitely might've tripped up people wasn't strictly considered a music video, so this is definitely a good indicator we should use.

# Further Data Cleaning

## Filtering the Watch history

Firstly, we'll need to combine video ids together in order to reduce the amount of API requests we're calling

In [144]:
start_index = 0
BATCH_SIZE = 50

combined_video_ids_batch = []

for start_index in range(start_index, len(records_dataframe), BATCH_SIZE):
    video_ids_batch = records_dataframe["video_ids"][start_index:start_index+BATCH_SIZE]
    combined_video_ids = ",".join(video_ids_batch)
    combined_video_ids_batch.append(combined_video_ids)

print(len(combined_video_ids_batch))

199

In [145]:
music_video_total = 0
for combined_video_ids_string in combined_video_ids_batch:
    watch_history_params = {
        "part": "snippet,contentDetails",
        "id": combined_video_ids_string,
        "key": api_key
    }

    watch_history_response = requests.get(url, params=watch_history_params)
    watch_history_data = watch_history_response.json()

    for item in watch_history_data["items"]:
        watch_history_snippet = item["snippet"]
        watch_history_content = item["contentDetails"]

        video_title = watch_history_snippet["title"]
        video_category = watch_history_snippet["categoryId"]

        if (video_category == "10"):
            print(f"{video_title} is considered a music video by YouTube's metadata")
            music_video_total += 1

print(f"Total music videos: {music_video_total}")

Unknown Mother Goose (wowaka) ♡ English Cover【rachie】アンノウン・マザーグース is considered a music video by YouTube's metadata
Aldnoah.Zero - "aLIEz" (FULL Ending) | ENGLISH ver | AmaLee is considered a music video by YouTube's metadata
"Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
monitoring (deco*27) ♥ english cover【rachie】モニタリング is considered a music video by YouTube's metadata
GUM&DROP / 星街すいせい (official) is considered a music video by YouTube's metadata
The Vampire (DECO*27) ♥ English Cover 【rachie】ヴァンパイア is considered a music video by YouTube's metadata
稲葉曇『ラグトレイン』Vo. 歌愛ユキ is considered a music video by YouTube's metadata
Official髭男dism - Pretender［Official Video］ is considered a music video by YouTube's metadata
【Ado】ギラギラ is considered a music video by YouTube's metadata
Midnight Grand Orchestra『Moonlightspeed 』Music Video is considered a music video by YouTube's metadata
「Yona Yona Journey / TAKU INOUE & Mori Calliope」MUSIC VIDEO is considered a music video by YouTube's metadata
Overdose - Kobo Kanaeru (Cover) is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
トレセン音頭 -下剋上 Ver- is considered a music video by YouTube's metadata
[Symphonic-Mobile Suite "UC"] 6thMob. :Unicorn Gundam is considered a music video by YouTube's metadata
ばかみたい【Taxi Driver Edition】 is considered a music video by YouTube's metadata
"Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee is considered a music video by YouTube's metadata
【AKASAKI】Bunny Girl / バニーガール（Lyric Video） is considered a music video by YouTube's metadata
No More What Ifs is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
【Ado】MIRROR is considered a music video by YouTube's metadata
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video) is considered a music video by YouTube's metadata
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble is considered a music video by YouTube's metadata
トレセン音頭 is considered a music video by YouTube's metadata
BLOW my GALE is considered a music video by YouTube's metadata
Ms. VICTORIA is considered a music video by YouTube's metadata
マーベラスサンデータイム☆★ is considered a music video by YouTube's metadata
GIRLS' LEGEND U is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
ツユ - それでも雨は降るんだね MV is considered a music video by YouTube's metadata
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】 is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
No More What Ifs is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video) is considered a music video by YouTube's metadata
【Ado】MIRROR is considered a music video by YouTube's metadata
星街すいせい - Stellar Stellar / THE FIRST TAKE is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】 is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
Tears of orphans is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき) is considered a music video by YouTube's metadata
三原色 - YOASOBI (Cover) / VESPERBELL × 松永依織 is considered a music video by YouTube's metadata
GIRLS' LEGEND U is considered a music video by YouTube's metadata
Umapyoi Celebrity is considered a music video by YouTube's metadata
トレセン音頭 is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
ツユ - それでも雨は降るんだね MV is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ] is considered a music video by YouTube's metadata
星街すいせい - Stellar Stellar / THE FIRST TAKE is considered a music video by YouTube's metadata
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire is considered a music video by YouTube's metadata
Tears of orphans is considered a music video by YouTube's metadata
凱旋門賞 最後の決戦 is considered a music video by YouTube's metadata
Set It Off - Why Do I is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
凱旋門賞 is considered a music video by YouTube's metadata
トレセン音頭 -下剋上 Ver- is considered a music video by YouTube's metadata
Umapyoi Celebrity is considered a music video by YouTube's metadata
チューリングカレアヤ is considered a music video by YouTube's metadata
Alekirser's Sleep Clinic is Open For Business (ASMR) is considered a music video by YouTube's metadata
トレセン音頭 is considered a music video by YouTube's metadata
GIRLS' LEGEND U is considered a music video by YouTube's metadata
【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】 is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire is considered a music video by YouTube's metadata
【Ado】MIRROR is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき) is considered a music video by YouTube's metadata
トレセン音頭 is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
that one mambo singing bohemian rhapsody video i found on twitter except she actually "sings" is considered a music video by YouTube's metadata
This Song Used to Be MY Song. It Still Is. is considered a music video by YouTube's metadata
Sakura Chiyono O doing workout is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
ヨルシカ - 盗作（OFFICIAL VIDEO） is considered a music video by YouTube's metadata
ねむるまち feat.yama  (Official Video) is considered a music video by YouTube's metadata
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】 is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
【Ado】MIRROR is considered a music video by YouTube's metadata
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video) is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
Set It Off - Why Do I is considered a music video by YouTube's metadata
Signs Of Love is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
BLOW my GALE is considered a music video by YouTube's metadata
Ms. VICTORIA is considered a music video by YouTube's metadata
トレセン音頭 is considered a music video by YouTube's metadata
Make a new track!! シニア級 is considered a music video by YouTube's metadata
Rivers In the Desert is considered a music video by YouTube's metadata
めにしゅき♡ラッシュっしゅ！ is considered a music video by YouTube's metadata
KOMM, SUSSER TOD M-10 Director's Edit Version | Evangelion Finally is considered a music video by YouTube's metadata
Umapyoi Celebrity is considered a music video by YouTube's metadata
When The Moon's Reaching Out Stars -Reload- is considered a music video by YouTube's metadata
No More What Ifs is considered a music video by YouTube's metadata
【MV】HELP!!  - Kobo Kanaeru is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
Set It Off - Why Do I is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
Why Eminem HATES doing commercials 🤬😳 is considered a music video by YouTube's metadata
アンノウン・マザーグース（cover）/ 相沢 is considered a music video by YouTube's metadata
【MV】HELP!!  - Kobo Kanaeru is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
Persona 5 ‖  With the Stars & Us ‖  ENGLISH ver. by @TheConsoulsBand  & Sapphire is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
【holo*27 MV】星街すいせい - プラネタリウム【ホロライブ x DECO*27】 is considered a music video by YouTube's metadata
Night Dancer - Imase [ Lyrics // Speed Up ] | Ui - Blue Archive Live2D is considered a music video by YouTube's metadata
Có Công mài "Sắc" - Ngô Lan hương [ Lyrics // Speed Up ] | Michiru (Dress) - Blue Archive Live2D is considered a music video by YouTube's metadata
【MV】HELP!!  - Kobo Kanaeru is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
アンノウン・マザーグース（cover）/ 相沢 is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
ウマすぎ！グルメパレード (Game Size) is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
ツユ - 過去に囚われている MV is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
Umapyoi Legend Typebeat (Collab remix) is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
ツユ - 過去に囚われている MV is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
アンノウン・マザーグース（cover）/ 相沢 is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
Ado - Dawn and Fireflies (夜明けと蛍) Lyrics w/ Furigana | [Kan/Rom/Eng] ふりがな 歌詞 - Yoake to Hotaru is considered a music video by YouTube's metadata
Official髭男dism - Pretender［Official Video］ is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
白日 / King Gnu (Covered by レヴィ・エリファ) is considered a music video by YouTube's metadata
Go To Sleep, She Isn't Coming Back. is considered a music video by YouTube's metadata
PT.2: Driving in my Car (Asgore Runs Over Dess) but heavenly. Animation by  @xmikamarble ​ is considered a music video by YouTube's metadata
Halo 3: ODST Disc 1 OST 04 Deference for Darkness is considered a music video by YouTube's metadata
"Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee is considered a music video by YouTube's metadata
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble is considered a music video by YouTube's metadata
SLOW + REVERB: Driving In My Car Asgore Runs Over Dess, but heavenly (Animation by @xmikamarble) is considered a music video by YouTube's metadata
【Ado】 唱 is considered a music video by YouTube's metadata
アンノウン・マザーグース（cover）/ 相沢 is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
Nightcrawlers - Push The Feeling On is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
Daredevil is considered a music video by YouTube's metadata
Alicorn is considered a music video by YouTube's metadata
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble is considered a music video by YouTube's metadata
【Ado】MIRROR is considered a music video by YouTube's metadata
アンノウン・マザーグース（cover）/ 相沢 is considered a music video by YouTube's metadata
Why Do I (with Hatsune Miku) is considered a music video by YouTube's metadata
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover) is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
Push The Feeling On - Nightcrawlers (Lyrics) is considered a music video by YouTube's metadata
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video) is considered a music video by YouTube's metadata
【Ado】踊 is considered a music video by YouTube's metadata
ツユ - 泥の分際で私だけの大切を奪おうだなんて MV is considered a music video by YouTube's metadata
ツユ - 過去に囚われている MV is considered a music video by YouTube's metadata
Natural selection 🥀 is considered a music video by YouTube's metadata
Mechanized Memories is considered a music video by YouTube's metadata
Armored Core 20th Anniversary Special Disk 02: 12 - Mechanized Memories - in the end - is considered a music video by YouTube's metadata
【Ado】ギラギラ is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】 is considered a music video by YouTube's metadata
八月、某、月明かり/ヨルシカ【弾き語りカバー】 is considered a music video by YouTube's metadata
星座になれたら/結束バンド【弾き語りカバー】 is considered a music video by YouTube's metadata
【City Pop】"平凡な毎日"こそ最高の贅沢。圧倒的多幸感に包まれるグルーヴィーチューン【Tosh Kamura - Ordinary, Extraordinary】 is considered a music video by YouTube's metadata
ただ君に晴れ/ヨルシカ【弾き語りカバー】 is considered a music video by YouTube's metadata
YOASOBI「群青」Official Music Video is considered a music video by YouTube's metadata
HIMEHINA×Nornis（戌亥とこ&町田ちま）『ブリキノダンス』Cover is considered a music video by YouTube's metadata
Shoshimin: How to become Ordinary Season 2 - Opening FULL "Martian" by Yorushika (Lyrics) is considered a music video by YouTube's metadata
【Cover】わたしのアール(和田たけあき) / 奏手イヅル is considered a music video by YouTube's metadata
八月、某、月明かり ver. nui is considered a music video by YouTube's metadata
めにしゅき♡ラッシュっしゅ！ is considered a music video by YouTube's metadata
【ウマ娘】Make debut! (パート分け/Color Coded/Lyrics)【ウマ娘1期OP】【メイクデビュー!】 is considered a music video by YouTube's metadata
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY is considered a music video by YouTube's metadata
【imase】NIGHT DANCER（MV） is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
Undertale Theme Medley - Acoustic Guitar Cover is considered a music video by YouTube's metadata
ムーンライト / 星街すいせい(official) is considered a music video by YouTube's metadata
mumei / 常闇トワ(cover) is considered a music video by YouTube's metadata
Ado - Dawn and Fireflies (夜明けと蛍) Lyrics w/ Furigana | [Kan/Rom/Eng] ふりがな 歌詞 - Yoake to Hotaru is considered a music video by YouTube's metadata
【Ado】ヒバナ 歌いました is considered a music video by YouTube's metadata
Ado - アイ・アイ・ア / THE FIRST TAKE is considered a music video by YouTube's metadata
At Bantam 🍷✨ Yakuza Bar/Cafe OST Mix is considered a music video by YouTube's metadata
tuki.『晩餐歌』Official Music Video is considered a music video by YouTube's metadata
【Ado】踊 is considered a music video by YouTube's metadata
【Ado】 唱 is considered a music video by YouTube's metadata
アンノウン・マザーグース（cover）/ 相沢 is considered a music video by YouTube's metadata
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ is considered a music video by YouTube's metadata
【Ado】MIRROR is considered a music video by YouTube's metadata
【Ado】ギラギラ is considered a music video by YouTube's metadata
【holo*27 MV】星街すいせい - プラネタリウム【ホロライブ x DECO*27】 is considered a music video by YouTube's metadata
ムーンライト / 星街すいせい(official) is considered a music video by YouTube's metadata
Official髭男dism - Pretender［Official Video］ is considered a music video by YouTube's metadata
【Ado】オールナイトレディオ is considered a music video by YouTube's metadata
STRANGER THAN HEAVEN Theme but the cleanest version is considered a music video by YouTube's metadata
【Kasane Teto SV2】STRANGER THAN HEAVEN (Unofficial Cover) is considered a music video by YouTube's metadata
Có Công mài "Sắc" - Ngô Lan hương [ Lyrics // Speed Up ] | Michiru (Dress) - Blue Archive Live2D is considered a music video by YouTube's metadata
【imase】NIGHT DANCER（MV） is considered a music video by YouTube's metadata

Ok, so of the 9945 watch history entries, only 630 songs that were considered songs by Youtube's metadata, which for being my main method of listening to music, is honestly quite low (that being said, I'd have to look deeper into the data, and additionally, the Hong Kong Japan trip likely would've put a damper on the data, If I Had done this say right now while in the semester, I'd say the ratio would be a lot better, it also doesn't help that Youtube changed their watch history logic such that any passing view counts as a view (in the case for Youtube statistics) which may be reflected in my own watch history, further diluting the pool. Fortunately, the process was incredibly quick at just 2 minutes and 3 seconds, which makes me interested if I were to take a longer range of time, how it would look.

Unfortunately, there is another issue, that being bad data, mainly false positives, you could break them up half and half into shorts and actual full videos.

With the shorts, my guess is that the ones that are either tagged as music or have a music artist as the subject were likley flagged as music, then there are the meme compilations by MrUnknown and the TV/Movie clips which confuse me.

As for the long form videos, they're a lot less dicpherable, some that are fully just music but whom i wouldn't necessarily consider its main entertainment subject, Sound Effects are particularly confusing, and then ASMR.....

## Shorts Classification

### Using Youtube's API to identify shorts

One of the major outliers I found checking the vidoes classified as music were Shorts, so an easy way to filter items would be to check if they are Shorts or not, and then if they aren't further checking before defining as music.

In [152]:
#The first 4 are the 4 most recent shorts in my watch history, the last 2 are definitively considered false positives

short_video_ids = ["TOKdln0vkrw", "Lg1QI8ZkPRU", "5OOE4WORb5Q", "R9922GyZmvw", "dq_4aV0uLus", "hgHR7AG3r6o", "p-BiFXlK268", "mrIYgy-xbyU", "K0mzD4i8AkI", "lV1RsohlBUc", "H66SAz682rc", "R7IfxRVT6ZQ", "mrIYgy-xbyU", "LY0p6VmRXbs"]

short_video_id = ",".join(short_video_ids)

short_params = {
    "part": "snippet,contentDetails",
    "id": short_video_id,
    "key": api_key
}

short_response = requests.get(url, params=short_params)
short_data = short_response.json()

for item in short_data["items"]:
    short_snippet = item["snippet"]
    short_content = item["contentDetails"]

    print("Title:", short_snippet["title"])
    print("Channel:", short_snippet["channelTitle"])
    print("Category:", short_snippet["categoryId"])
    print("Duration:", short_content["duration"])
    print("Tags:", short_snippet.get("tags", []))
    print("")

Title: Mario Kart 8 Deluxe Players are Going Insane right now...
Channel: Shortcat
Category: 20
Duration: PT1M49S
Tags: []

Title: Oops! Nintendo reveals Mario Kart 8's DEBUG mode
Channel: Beta64
Category: 20
Duration: PT58S
Tags: ['beta 64', 'beta64', 'beta', 'video game history', 'documentary', 'lost media', 'proto', 'prototype', 'beta build', 'trailer', 'early', 'unused', 'scrapped', 'interview', 'mario kart 8', 'mario kart 8 deluxe', 'wii u', 'switch', 'mario kart world', 'mario kart', 'kiosk demo', 'mario kart 8 demo', 'mario kart 8 beta', 'nintendo direct', 'mario kart 8 deluxe kiosk demo', 'debug mode', 'mario kart 8 debug']

Title: I Love These Uma Musume
Channel: Starfang
Category: 20
Duration: PT16S
Tags: []

Title: 第三方居然出了MG飛昇自由？大砲還有拉伸結構，還可以全彈髮射！ #gundam #갓건담 #gunpla #bandai #高達 #toys #萬代
Channel: 玩具測評總動員
Category: 24
Duration: PT31S
Tags: []

Title: Natural selection 🥀
Channel: MrUnknown
Category: 10
Duration: PT15S
Tags: []

Title: He noticed the actor’s lines slowed down on TV and kidnapped him for diagnosis#house #fyp
Channel: Velvet Karol
Category: 10
Duration: PT2M52S
Tags: []

Title: Why did you steal my stuff #MD
Channel: Sarah Duncan
Category: 10
Duration: PT2M29S
Tags: ['Sarah Duncan']

Title: tucker bryne Discovers Rice showers dangerous fangs #umamusume #umamusumememes #ytshorts #riceshower
Channel: attouです
Category: 10
Duration: PT35S
Tags: []

Title: Marvey | Toki yo tomare【時よ止まれ】 #umamusume #mmd
Channel: Heyvae
Category: 10
Duration: PT36S
Tags: []

Title: Why Eminem HATES doing commercials 🤬😳
Channel: Music Media
Category: 10
Duration: PT33S
Tags: ['eminem', 'funny', 'rap', 'edit']

Title: Fat Chud (ft. Adachi Rei & Kasane Teto)
Channel: Alex.Read626
Category: 10
Duration: PT14S
Tags: []

Title: Hatsune Miku’s Microphone STOPS WORKING?!  #hatsunemikuvocaloid #mikuexpo #miku
Channel: 🩵 • Miku Fanpage • 🎤
Category: 10
Duration: PT21S
Tags: ['Miku', 'Hatsune', 'Hatsune Miku', 'Vocaloid', 'Concert', 'Vocaloid Concrt', 'MikuExpo', 'Miku Expo', 'MikuExpo 2024', 'Miku Expo 2024']

Title: tucker bryne Discovers Rice showers dangerous fangs #umamusume #umamusumememes #ytshorts #riceshower
Channel: attouです
Category: 10
Duration: PT35S
Tags: []

Title: ADO MINECRAFT CORE
Channel: AkaneMikkyo
Category: 10
Duration: PT48S
Tags: ['ado', 'ado cute', 'ado vtuber', 'ado core', 'ado silly', 'fpy', 'adomination', 'adosolos', 'uta', 'songstress', 'iloveado', 'tiktok', 'tiktoktrend', 'ViralVideo', 'JPopIdols', 'JapaneseCulture', 'JapaneseLyrics', 'This is so Ado', 'ADO WORLD DOMINATION', 'If not wife then why wife shaped', 'うっせぇわ', 'ADO MINECRAFT CORE']

Unfortunately, there isnt any other data that we can use to identify a common behaviour (aside from duration, which at this point, feels a little dubious to use as our smoking gun), however there might be another avenue to use:

YouTube itself knows whether a video is a Short because the website routes Shorts through its /shorts/VIDEO_ID interface.

So instead of asking the Data API whether something is a Short, we may be able to ask YouTube's public web interface indirectly.
Conceptually:
video ID
   │
   ├── Data API ──────→ metadata/music classification
   │
   └── YouTube web ───→ does YouTube treat this ID as a Short?

In [158]:
known_short = "hgHR7AG3r6o"       # House clip, 2m52s
known_long = "oMuyO2tFDwg"              # Nicewigg ALGS video, 1h36m57s

short_url = f"https://www.youtube.com/shorts/{known_short}"
long_url = f"https://www.youtube.com/shorts/{known_long}"

short_response = requests.get(short_url)
long_response = requests.get(long_url)

print("URLs before being sent to Youtube API, notice how we sending both links to be viewed via the shorts player, even though we know one of them is a long form video\n")
print(short_url)
print(long_url)


print("\nSHORT:")
print(short_response.status_code)
print(short_response.url)
print("SHORT HISTORY:")
print(short_response.history)

print("\nLONG:")
print(long_response.status_code)
print(long_response.url)
print("LONG HISTORY:")
print(long_response.history)

URLs before being sent to Youtube API, notice how we sending both links to be viewed via the shorts player, even though we know one of them is a long form video

https://www.youtube.com/shorts/hgHR7AG3r6o
https://www.youtube.com/shorts/oMuyO2tFDwg
SHORT:
200
https://www.youtube.com/shorts/hgHR7AG3r6o
SHORT HISTORY:
[]

LONG:
200
https://www.youtube.com/watch?v=oMuyO2tFDwg&pp=0gcJCW8CQVKahPAF
LONG HISTORY:
[<Response [303]>]

In the code above, We tried to force a long form video to be viewed as a short, but it redirected back to the long form video. This should make up the basic function that we can use to easily determine if a video is a short, if we force it into a short, and it redirects as a short, we can classify it as a short and hence then cut it out from our history.

In [162]:
def is_short(video_id):
    video_url = f"https://www.youtube.com/shorts/{video_id}"
    response = requests.get(video_url)

    if "/shorts/" in response.url:
        return True

    #print(response.status_code)
    #print(response.url)
    return False

known_short_video_ids = ["dq_4aV0uLus", "hgHR7AG3r6o", "p-BiFXlK268", "mrIYgy-xbyU", "K0mzD4i8AkI", "lV1RsohlBUc", "H66SAz682rc", "R7IfxRVT6ZQ", "mrIYgy-xbyU"] #All videos are considred music at this stage
known_long_video_ids = ["uRDuw9BpnmY", "tab1yUu20gA", "oMuyO2tFDwg", "qQ6oJR6Ki9s", "UTcwnCz4-UY", "xnzfxv9J1KE", "4h0Ht6JyCxc", "RlDZgZvIQ5U"] #5 videos not considred music, 5 considered music

for known_short_video_id in known_short_video_ids:
    if is_short(known_short_video_id):
        print(f"{known_short_video_id} is a short video")
    else:
        print(f"{known_short_video_id} is not a short video")

for known_long_video_id in known_long_video_ids:
    if is_short(known_long_video_id):
        print(f"{known_long_video_id} is not a long video, it's a short video")
    else:
        print(f"{known_long_video_id} is a long video")

dq_4aV0uLus is a short video
hgHR7AG3r6o is a short video
p-BiFXlK268 is a short video
mrIYgy-xbyU is a short video
K0mzD4i8AkI is a short video
lV1RsohlBUc is a short video
H66SAz682rc is a short video
R7IfxRVT6ZQ is a short video
mrIYgy-xbyU is a short video
uRDuw9BpnmY is a long video
tab1yUu20gA is a long video
oMuyO2tFDwg is a long video
qQ6oJR6Ki9s is a long video
UTcwnCz4-UY is a long video
xnzfxv9J1KE is a long video
4h0Ht6JyCxc is a long video
RlDZgZvIQ5U is a long video

### Integrating Shorts classification with Music classification

In [191]:
BATCH_SIZE = 50

def create_video_batches(dataframe):
    combined_video_ids_batch = []

    for start_index in range(0, len(dataframe), BATCH_SIZE):
        video_ids_batch = dataframe["video_ids"][
            start_index:start_index + BATCH_SIZE
        ]

        combined_video_ids = ",".join(video_ids_batch)
        combined_video_ids_batch.append(combined_video_ids)

    return combined_video_ids_batch

def check_music_candidates(music_candidate_ids):
    true_music_candidates = []

    for music_candidate in music_candidate_ids:
        if is_short(music_candidate.get("video_ID")):
            print(f"{music_candidate.get("video_title")} is a short video")

        else:
            #print(f"{music_candidate.get("video_title")} is a long-form music video")
            true_music_candidates.append(music_candidate)

    return true_music_candidates

video_batches = create_video_batches(records_dataframe)
music_candidates = []

for combined_video_ids_string in video_batches:

    # API request...
    watch_history_params = {
        "part": "snippet,contentDetails",
        "id": combined_video_ids_string,
        "key": api_key
    }

    watch_history_response = requests.get(url, params=watch_history_params)
    watch_history_data = watch_history_response.json()

    for item in watch_history_data["items"]:
        snippet = item["snippet"]
        content = item["contentDetails"]

        video_id = item["id"]
        video_title = snippet["title"]
        video_category = snippet["categoryId"]
        channel_name = snippet["channelTitle"]
        channel_id = snippet["channelId"]

        if video_category == "10":
            music_candidate_entry = {
                "video_title": video_title,
                "video_ID": video_id,
                "channel_name": channel_name,
                "channel_id": channel_id,
            }
            music_candidates.append(music_candidate_entry)

actual_candidates = check_music_candidates(music_candidates)

print(f"{len(actual_candidates)} music candidates found")
for candidate in actual_candidates:
    print(f"{candidate.get("video_title")}")

Why Eminem HATES doing commercials 🤬😳 is a short video
PT.2: Driving in my Car (Asgore Runs Over Dess) but heavenly. Animation by  @xmikamarble ​ is a short video
Natural selection 🥀 is a short video
Bro MIGHT be the smartest ✌️ is a short video
Wonder what his barber does for a living 🥀 is a short video
Historically accurate tho 🙏 is a short video
They just took a hydration break 🥀 is a short video
Teach moving like John Wick ✌️ is a short video
He sounded so mad at chase 😭 is a short video
Bro understood the consequences ✌️ is a short video
"Coming early for tomorrow?" 💔 is a short video
First guy deserves an Oscar 😭 is a short video
"Half day huh?" 💔 is a short video
Bro picked the pro kids 🥀 is a short video
fat little chud teto cover #重音テト #synthesizerv is a short video
He noticed the actor’s lines slowed down on TV and kidnapped him for diagnosis#house #fyp is a short video
”You got any games on your phone?” 🥀 is a short video
Why did you steal my stuff #MD is a short video
Loki even became a scientist for his friend!#edit #shorts #shortvideo #marvel #mcu #loki is a short video
Loki discovered a secret during the final days of Pompeii.#edit #shorts #shortvideo #marvel #mcu is a short video
tucker bryne Discovers Rice showers dangerous fangs #umamusume #umamusumememes #ytshorts #riceshower is a short video
Bro had to ask Gods permission 🙏 is a short video
Special week with her two daughters #umamusume #fypshort #specialweek #buenavista #cesario #cute is a short video
Carats have had enough of Teio #umamusume #umamusumememes #ytshorts #tokaiteio #carats #darkhumor is a short video
Mischievous Haru Urara thought she wasn't noticed #umamusume #umamusumememes #ytshorts #haruurara is a short video
Ado aura core is a short video
Ado reaction to her memes | Ado core is a short video
Fat Chud (ft. Adachi Rei & Kasane Teto) is a short video
Marvey | Toki yo tomare【時よ止まれ】 #umamusume #mmd is a short video
Hatsune Miku’s Microphone STOPS WORKING?!  #hatsunemikuvocaloid #mikuexpo #miku is a short video
Fukukitaru | otsukare [Umamusume MMD] #umamusume #mmd is a short video
Fukukitaru | otsukare [Umamusume MMD] #umamusume #mmd is a short video
598 music candidates found
Unknown Mother Goose (wowaka) ♡ English Cover【rachie】アンノウン・マザーグース
Aldnoah.Zero - "aLIEz" (FULL Ending) | ENGLISH ver | AmaLee
"Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
monitoring (deco*27) ♥ english cover【rachie】モニタリング
GUM&DROP / 星街すいせい (official)
The Vampire (DECO*27) ♥ English Cover 【rachie】ヴァンパイア
稲葉曇『ラグトレイン』Vo. 歌愛ユキ
Official髭男dism - Pretender［Official Video］
【Ado】ギラギラ
Midnight Grand Orchestra『Moonlightspeed 』Music Video
「Yona Yona Journey / TAKU INOUE & Mori Calliope」MUSIC VIDEO
Overdose - Kobo Kanaeru (Cover)
Why Do I (with Hatsune Miku)
トレセン音頭 -下剋上 Ver-
[Symphonic-Mobile Suite "UC"] 6thMob. :Unicorn Gundam
ばかみたい【Taxi Driver Edition】
"Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee
【AKASAKI】Bunny Girl / バニーガール（Lyric Video）
No More What Ifs
Why Do I (with Hatsune Miku)
【Ado】MIRROR
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble
トレセン音頭
BLOW my GALE
Ms. VICTORIA
マーベラスサンデータイム☆★
GIRLS' LEGEND U
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
ツユ - それでも雨は降るんだね MV
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
白日 / King Gnu (Covered by レヴィ・エリファ)
No More What Ifs
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
Why Do I (with Hatsune Miku)
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
【Ado】MIRROR
星街すいせい - Stellar Stellar / THE FIRST TAKE
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
【Ado】オールナイトレディオ
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
STRANGER THAN HEAVEN Theme but the cleanest version
Tears of orphans
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき)
三原色 - YOASOBI (Cover) / VESPERBELL × 松永依織
GIRLS' LEGEND U
Umapyoi Celebrity
トレセン音頭
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
ツユ - それでも雨は降るんだね MV
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ]
星街すいせい - Stellar Stellar / THE FIRST TAKE
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire
Tears of orphans
凱旋門賞 最後の決戦
Set It Off - Why Do I
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
凱旋門賞
トレセン音頭 -下剋上 Ver-
Umapyoi Celebrity
チューリングカレアヤ
Alekirser's Sleep Clinic is Open For Business (ASMR)
トレセン音頭
GIRLS' LEGEND U
【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】
白日 / King Gnu (Covered by レヴィ・エリファ)
Why Do I (with Hatsune Miku)
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire
【Ado】MIRROR
【Ado】オールナイトレディオ
白日 / King Gnu (Covered by レヴィ・エリファ)
【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき)
トレセン音頭
Why Do I (with Hatsune Miku)
that one mambo singing bohemian rhapsody video i found on twitter except she actually "sings"
This Song Used to Be MY Song. It Still Is.
Sakura Chiyono O doing workout
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
白日 / King Gnu (Covered by レヴィ・エリファ)
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire
STRANGER THAN HEAVEN Theme but the cleanest version
ヨルシカ - 盗作（OFFICIAL VIDEO）
ねむるまち feat.yama  (Official Video)
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】
【Ado】オールナイトレディオ
【Ado】MIRROR
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Set It Off - Why Do I
Signs Of Love
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
BLOW my GALE
Ms. VICTORIA
トレセン音頭
Make a new track!! シニア級
Rivers In the Desert
めにしゅき♡ラッシュっしゅ！
KOMM, SUSSER TOD M-10 Director's Edit Version | Evangelion Finally
Umapyoi Celebrity
When The Moon's Reaching Out Stars -Reload-
No More What Ifs
【MV】HELP!!  - Kobo Kanaeru
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Set It Off - Why Do I
Why Do I (with Hatsune Miku)
アンノウン・マザーグース（cover）/ 相沢
【MV】HELP!!  - Kobo Kanaeru
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
白日 / King Gnu (Covered by レヴィ・エリファ)
STRANGER THAN HEAVEN Theme but the cleanest version
Persona 5 ‖  With the Stars & Us ‖  ENGLISH ver. by @TheConsoulsBand  & Sapphire
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
【holo*27 MV】星街すいせい - プラネタリウム【ホロライブ x DECO*27】
Night Dancer - Imase [ Lyrics // Speed Up ] | Ui - Blue Archive Live2D
Có Công mài "Sắc" - Ngô Lan hương [ Lyrics // Speed Up ] | Michiru (Dress) - Blue Archive Live2D
【MV】HELP!!  - Kobo Kanaeru
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
STRANGER THAN HEAVEN Theme but the cleanest version
アンノウン・マザーグース（cover）/ 相沢
白日 / King Gnu (Covered by レヴィ・エリファ)
ウマすぎ！グルメパレード (Game Size)
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
STRANGER THAN HEAVEN Theme but the cleanest version
ツユ - 過去に囚われている MV
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble
【Ado】オールナイトレディオ
Umapyoi Legend Typebeat (Collab remix)
白日 / King Gnu (Covered by レヴィ・エリファ)
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
STRANGER THAN HEAVEN Theme but the cleanest version
ツユ - 過去に囚われている MV
【Ado】オールナイトレディオ
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
アンノウン・マザーグース（cover）/ 相沢
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Ado - Dawn and Fireflies (夜明けと蛍) Lyrics w/ Furigana | [Kan/Rom/Eng] ふりがな 歌詞 - Yoake to Hotaru
Official髭男dism - Pretender［Official Video］
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
白日 / King Gnu (Covered by レヴィ・エリファ)
Go To Sleep, She Isn't Coming Back.
Halo 3: ODST Disc 1 OST 04 Deference for Darkness
"Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble
SLOW + REVERB: Driving In My Car Asgore Runs Over Dess, but heavenly (Animation by @xmikamarble)
【Ado】 唱
アンノウン・マザーグース（cover）/ 相沢
【Ado】オールナイトレディオ
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
STRANGER THAN HEAVEN Theme but the cleanest version
Nightcrawlers - Push The Feeling On
Why Do I (with Hatsune Miku)
STRANGER THAN HEAVEN Theme but the cleanest version
Daredevil
Alicorn
Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble
【Ado】MIRROR
アンノウン・マザーグース（cover）/ 相沢
Why Do I (with Hatsune Miku)
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Push The Feeling On - Nightcrawlers (Lyrics)
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
【Ado】踊
ツユ - 泥の分際で私だけの大切を奪おうだなんて MV
ツユ - 過去に囚われている MV
Mechanized Memories
Armored Core 20th Anniversary Special Disk 02: 12 - Mechanized Memories - in the end -
【Ado】ギラギラ
STRANGER THAN HEAVEN Theme but the cleanest version
だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】
八月、某、月明かり/ヨルシカ【弾き語りカバー】
星座になれたら/結束バンド【弾き語りカバー】
【City Pop】"平凡な毎日"こそ最高の贅沢。圧倒的多幸感に包まれるグルーヴィーチューン【Tosh Kamura - Ordinary, Extraordinary】
ただ君に晴れ/ヨルシカ【弾き語りカバー】
YOASOBI「群青」Official Music Video
HIMEHINA×Nornis（戌亥とこ&町田ちま）『ブリキノダンス』Cover
Shoshimin: How to become Ordinary Season 2 - Opening FULL "Martian" by Yorushika (Lyrics)
【Cover】わたしのアール(和田たけあき) / 奏手イヅル
八月、某、月明かり ver. nui
めにしゅき♡ラッシュっしゅ！
【ウマ娘】Make debut! (パート分け/Color Coded/Lyrics)【ウマ娘1期OP】【メイクデビュー!】
【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY
【imase】NIGHT DANCER（MV）
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
Undertale Theme Medley - Acoustic Guitar Cover
ムーンライト / 星街すいせい(official)
mumei / 常闇トワ(cover)
Ado - Dawn and Fireflies (夜明けと蛍) Lyrics w/ Furigana | [Kan/Rom/Eng] ふりがな 歌詞 - Yoake to Hotaru
【Ado】ヒバナ 歌いました
Ado - アイ・アイ・ア / THE FIRST TAKE
At Bantam 🍷✨ Yakuza Bar/Cafe OST Mix
tuki.『晩餐歌』Official Music Video
【Ado】踊
【Ado】 唱
アンノウン・マザーグース（cover）/ 相沢
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
【Ado】MIRROR
【Ado】ギラギラ
【holo*27 MV】星街すいせい - プラネタリウム【ホロライブ x DECO*27】
ムーンライト / 星街すいせい(official)
Official髭男dism - Pretender［Official Video］
【Ado】オールナイトレディオ
STRANGER THAN HEAVEN Theme but the cleanest version
【Kasane Teto SV2】STRANGER THAN HEAVEN (Unofficial Cover)
Có Công mài "Sắc" - Ngô Lan hương [ Lyrics // Speed Up ] | Michiru (Dress) - Blue Archive Live2D
【imase】NIGHT DANCER（MV）
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Overlord Season 4 Ending | Mayu Maeshima - 「No Man's Dawn」
Mobile Suit Gundam Iron Blooded Orphans Urdr Hunt OST - Red vs Blue [Extended]
ヨルシカをメドレーにして1人でバンドしてみた -Yorushika Medley One man Band Cover
POV: you're in love with a memory | Playlist
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
Imagine Dragons – Take Me To The Beach (Amazon Music Songline)
Prison Labor - Persona 5 Royal OST [Extended]
Umapyoi Celebrity
【和風アレンジ】ツユ - レインフォール cover-カバー-
【アコギ】ヨルシカ Acoustic Guitarメドレー2【全12曲】
夜明けと蛍（cover）/ 相沢
君の知らない物語（cover）/ 相沢
メルト（cover）/ 相沢
アンノウン・マザーグース（cover）/ 相沢
奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ
ヨルシカをメドレーにして1人でバンドしてみた -Yorushika Medley One man Band Cover
結束バンドメドレーをぼっちでバンドしてみた
星街すいせいメドレーを一人でバンド組んで歌ってみた
Undertale Theme Medley - Acoustic Guitar Cover
アンノウン・マザーグース（cover）/ 相沢
STRANGER THAN HEAVEN Theme but the cleanest version
GIRLS' LEGEND U
めにしゅき♡ラッシュっしゅ！
【ウマ娘】ユメヲカケル! (カノープスVer) (パート分け/Color Coded/Lyrics)【Run for Our Dream】
Day After Day
Mechanized Memories
Armored Core 20th Anniversary Special Disk 02: 12 - Mechanized Memories - in the end -
[MAMBOCORE] Blinding Lights
あの世行きのバスに乗ってさらば。Full acoustic version by ツユ/TUYU
Ghost City Tokyo ♡ English Cover【rachie】幽霊東京
【MV】HELP!!  - Kobo Kanaeru
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
うまぴょい伝説
GIRLS' LEGEND U ―やっとみんな会えたね―
マーベラスサンデータイム☆★
ウマすぎ！グルメパレード
Ms. VICTORIA
BLOW my GALE
【Ado】 唱
ヨルシカ - 千鳥（OFFICIAL VIDEO）
ムーンライト / 星街すいせい(official)
【Ado】MIRROR
【Ado】オールナイトレディオ
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
Breaking Bad Theme
Stranger Than Heaven Trailer Song「 HQ Full Remake 」NO-AI
稲葉曇『ロストアンブレラ』Vo. 歌愛ユキ
【Ado】ヒバナ 歌いました
めにしゅき♡ラッシュっしゅ！
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
Why Do I (with Hatsune Miku)
STRANGER THAN HEAVEN Theme but the cleanest version
[HOLOLIVE ID] KOBO KANAERU FT. MORI CALLIOPE 'ENDLESS TEARS' CLIFF EDGE LYRICS (Color Coded Lyrics)
【MV】HELP!!  - Kobo Kanaeru
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
アンノウン・マザーグース（cover）/ 相沢
【AKASAKI】Bunny Girl / バニーガール（Lyric Video）
Official髭男dism - Pretender［Official Video］
【Ado】ギラギラ
ムーンライト / 星街すいせい(official)
【holo*27 MV】星街すいせい - プラネタリウム【ホロライブ x DECO*27】
ヨルシカ - あぶく（OFFICIAL VIDEO）
タイニーリトル・アジアンタム
稲葉曇『ラグトレイン』Vo. 歌愛ユキ
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
Why Do I (with Hatsune Miku)
【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】
GIRLS' LEGEND U
Ms. VICTORIA
うまぴょい伝説
アンノウン・マザーグース（cover）/ 相沢
ウマすぎ！グルメパレード
マーベラスサンデータイム☆★
めにしゅき♡ラッシュっしゅ！
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Why Do I (with Hatsune Miku)
Armored Core 20th Anniversary Special Disk 02: 12 - Mechanized Memories - in the end -
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
STRANGER THAN HEAVEN Theme but the cleanest version
GUNDAM BUILD FIGHTERS ost [The Crimson Comet ～Three Times The Passion Of Ordinary Flamenco～]
アンノウン・マザーグース（cover）/ 相沢
Overdose - Kobo Kanaeru (Cover)
【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】
Blackbear - "Idfc" (Acoustic) OFFICIAL VERSION
【MV】HELP!!  - Kobo Kanaeru
Why Do I (with Hatsune Miku)
【GhostFinal & Kinoko蘑菇】1 2 beat「Girls' Frontline 2: Exilium OST」【ドールズフロントライン2：エクシリウム】Official
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
アンノウン・マザーグース（cover）/ 相沢
I'm a chud song (Kasane Teto Cover)
STRANGER THAN HEAVEN Theme but the cleanest version
See Tình x Ai Đưa Em Về (Switching Vocals) / Nightcore
強欲
Ado - Unknown Mother Goose Live.
Imagine Dragons - Bones (Official Lyric Video)
Overdose - Kobo Kanaeru (Cover)
Hikaru Utada & Skrillex - Face My Fears [Official Video]
Ms. VICTORIA
HOT LIMIT - From THE FIRST TAKE
【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】
Ms. VICTORIA
【ウマ娘】BLOW my GALE (パート分け/Color Coded/Lyrics)【Make a new track!!】
白日 (Hakujitsu) - King Gnu // covered by 道明寺ここあ
I'm a chud song (Kasane Teto Cover)
What You Wish For - Persona 5 Scramble: The Phantom Strikers
Axe to Grind - Persona 5 Scramble: The Phantom Strikers
Yorushika - Evening Calm, Somewhere, Fireworks (夕凪、某、花惑い) (Lyrics/Kan/Rom/Eng)
ヨルシカ - 八月、某、月明かり（OFFICIAL VIDEO）
Deep Indigo -piano and drums arrange- ♡ English Cover【rachie】藍二乗
【Ado】ヒバナ 歌いました
【和風アレンジ】ツユ - レインフォール cover-カバー-
白日 (Hakujitsu) - King Gnu // covered by 道明寺ここあ
【Rainych】 SAY SO - Doja Cat | Japanese Version (cover)
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
STRANGER THAN HEAVEN Theme but the cleanest version
Stranger Than Heaven
Yuki Hayashi - GBF (OpenTheFutureMix)
Yuki Hayashi - Out of the Way, Small Fry
トレセン音頭 -下剋上 Ver-
Umapyoi Celebrity
Surface of the Iron-Blooded Orphans
天球、彗星は夜を跨いで / 星街すいせい(official)
稲葉曇『ロストアンブレラ』Vo. 歌愛ユキ
Lagtrain (ラグトレイン) | Moonbase Alpha Cover |【DECtalk Paul VCV】【UTAUカバー】
Donut Hole (ドーナツホール) | Moonbase Alpha Cover |【DECtalk Paul VCV】【UTAUカバー】
Official髭男dism - Pretender［Official Video］
Midnight Grand Orchestra『Moonlightspeed 』Music Video
Why Do I (with Hatsune Miku)
I got a little too excited
Blackbear - "Idfc" (Acoustic) OFFICIAL VERSION
Yorushika - Evening Calm, Somewhere, Fireworks (夕凪、某、花惑い) (Lyrics/Kan/Rom/Eng)
Umapyoi Celebrity
トレセン音頭
戰鬥男孩
Play Again
I'm a chud song (Kasane Teto Cover)
Alekirser's Sleep Clinic is Open For Business (ASMR)
Flashbacker
Rivers In the Desert
Yuki Hayashi - Out of the Way, Small Fry
Yuki Hayashi - GBF (OpenTheFutureMix)
Why Do I (with Hatsune Miku)
めにしゅき♡ラッシュっしゅ！
Splatoon Cover - Idol (Full Version)
【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】
YOASOBI「怪物」/スターアニマル (ときのそら・星街すいせい・大空スバル・尾丸ポルカ・博衣こより・沙花叉クロヱ) cover
【ウマ娘】BLOW my GALE (パート分け/Color Coded/Lyrics)【Make a new track!!】
Ms. VICTORIA
【和風アレンジ】ツユ - レインフォール cover-カバー-
Yorushika - Evening Calm, Somewhere, Fireworks (夕凪、某、花惑い) (Lyrics/Kan/Rom/Eng)
夕凪、某、花惑い - ヨルシカ （Yuunagi, Bou, Hana Madoi - Yorushika）/ 【月-Tsuki- COVER】
いじめっ子Bully （Lofi Ver.）
A WAY OF LIFE (Cover)「Persona 3 Portable」/ ver.jen
Persona 3 Portable: A Way of Life
Overdose - Kobo Kanaeru (Cover)
Ghost City Tokyo ♡ English Cover【rachie】幽霊東京
「3時12分 / TAKU INOUE & 星街すいせい」MUSIC VIDEO
Midnight Grand Orchestra『Moonlightspeed 』Music Video
STRANGER THAN HEAVEN Theme but the cleanest version
STRANGER THAN HEAVEN Theme but the cleanest version
Prison Labor - Persona 5 Royal OST [Extended]
Warframe OST - The Sacrifice - To Take Its Pain Away (Smiles From Juran)
Seisyunbutayaro
3. いつかの記憶 Memories of Someday | Makeine: Too Many Losing Heroines! OST Vol. 1
2. 華色の青春 Flower-Colored Youth | Makeine: Too Many Losing Heroines! OST Vol. 1
1. 負けヒロインのテーマ Losing Heroine's Theme | Makeine: Too Many Losing Heroines! OST Vol. 1
Why Do I (with Hatsune Miku)
STRANGER THAN HEAVEN Theme but the cleanest version
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Prison Labor - Persona 5 Royal OST [Extended]
【ウマ娘】BLOW my GALE (パート分け/Color Coded/Lyrics)【Make a new track!!】
Imagine Dragons - Bones (Official Lyric Video)
Metal Gear Rising: Revengeance OST - A Stranger I Remain Extended
【龍が如くスタジオ】STRANGER THAN HEAVENを熱演する鳩に釘付けになる人々!! 【Ado,藤原聡(Official髭男dism),Tori Kelly,Snoop Dogg】
【Kasane Teto SV2】STRANGER THAN HEAVEN (Unofficial Cover)
Stranger Than Heaven
Make a new track!! シニア級
トレセン音頭 -ぐだぐだ Ver-
トレセン音頭 -雅 Ver-
STRANGER THAN HEAVEN Theme but the cleanest version
ADO MINECRAFT CORE
【YOASOBI🌷】全有名曲メドレー ｜Study with me｜Work with me｜リラックスタイム｜安眠・癒し・作業用BGM｜勉強用BGM｜AnnieChan_playlist ⑤
YOASOBI「ハルジオン」Official Music Video
YOASOBI「たぶん」Official Music  Video
Ms. VICTORIA
It's Going Down Now
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
Ms. VICTORIA
Prison Labor - Persona 5 Royal OST [Extended]
Prison Labor - Persona 5 The Royal
Your Affection
Signs Of Love
Persona 3 Portable: A Way of Life
Heaven
Rivers In the Desert
Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video)
ROAD LESS TAKEN
Axe to Grind - Persona 5 Scramble: The Phantom Strikers
What You Wish For - Persona 5 Scramble: The Phantom Strikers
灰色と青/常闇トワ×星街すいせい(cover)
僕が死のうと思ったのは (Covered by レヴィ・エリファ)
Umapyoi Celebrity
H4R1K1TTE 1K0U! feat. Kitasan Black (Umamusume Type Beat)
YOASOBI「怪物」/スターアニマル (ときのそら・星街すいせい・大空スバル・尾丸ポルカ・博衣こより・沙花叉クロヱ) cover
Splatoon Cover - Idol (Full Version)
Idol (アイドル) | Moonbase Alpha Cover |【DECtalk Paul VCV】【UTAUカバー】-4.5K Subscriber Special!!!
ヨルシカ - 八月、某、月明かり（OFFICIAL VIDEO）
【和風アレンジ】ツユ - レインフォール cover-カバー-
Deep Indigo -piano and drums arrange- ♡ English Cover【rachie】藍二乗
Lagtrain (ラグトレイン) | Moonbase Alpha Cover |【DECtalk Paul VCV】【UTAUカバー】
稲葉曇『ロストアンブレラ』Vo. 歌愛ユキ
天球、彗星は夜を跨いで / 星街すいせい(official)
Donut Hole (ドーナツホール) | Moonbase Alpha Cover |【DECtalk Paul VCV】【UTAUカバー】
harikitte ikou
This Is What You Are
This convinces me that Ado’s just Bocchi but singer
Warframe OST - The Sacrifice - To Take Its Pain Away (Smiles From Juran)
When You Flinch – Original ASMR Duet
Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover)
See Tình x Ai Đưa Em Về (Switching Vocals) / Nightcore
Nightcore - Legends Never Die / NMV
Nightcore → Ai Đưa Em Về (Take me back, back home) - That Low Cortisol Song!
Umapyoi Celebrity
トレセン音頭 -下剋上 Ver-
Ms. VICTORIA
Imagine Dragons - Bones (Official Lyric Video)

A really good passthrough, we caught 32 shorts from our list alone, which is great, of course, there are a still a bunch of outliers, but now we'll use Official channels and keywords to further refine that

## Official Channel/Topic Classification

### Using Youtube's API to request Channel metadata

Firstly, we'll need to look at the metadata on the channels from the video, we're inspecting

In [179]:
music_video_id = records_dataframe.loc[168, "video_ids"]
music_video_title = records_dataframe.loc[168,"title"]

print(f'The video: {music_video_title}, has the video id: {music_video_id}')

channel_url = "https://www.googleapis.com/youtube/v3/channels"

music_params = {
    "part": "snippet,contentDetails",
    "id": music_video_id,
    "key": api_key
}

music_video_response = requests.get(url, params=music_params)

music_video_data = music_video_response.json()
non_music_video_data = non_music_video_response.json()


mv_snippet = mv_item["snippet"]
mv_item = music_video_data["items"][0]
SIO_channel_name = mv_snippet["channelTitle"]
SIO_channel_id = mv_item["snippet"]["channelId"]

print(f"The Channel ID for {SIO_channel_name} who published {mv_snippet["title"]} is {SIO_channel_id}")

channel_params = {
    "part": "snippet,contentDetails,statistics,topicDetails",
    "id": SIO_channel_id,
    "key": api_key
}

channel_response = requests.get(channel_url, params=channel_params)

print(channel_response.status_code)

channel_data = channel_response.json()
channel_item = channel_data["items"][0]

#print(channel_item)

The video: Why Do I (with Hatsune Miku), has the video id: HMFNXgu7L3Q
The Channel ID for Set It Off who published Why Do I (with Hatsune Miku) is UCB1bJqKXS3lpy8HdW0P1zrQ
200
{'topicIds': ['/m/064t9', '/m/04rlf', '/m/06by7', '/m/02lkt'], 'topicCategories': ['https://en.wikipedia.org/wiki/Pop_music', 'https://en.wikipedia.org/wiki/Music', 'https://en.wikipedia.org/wiki/Rock_music', 'https://en.wikipedia.org/wiki/Electronic_music']}

In [178]:
print(channel_item.get("topicDetails"))

{'topicIds': ['/m/02lkt', '/m/064t9', '/m/04rlf', '/m/06by7'], 'topicCategories': ['https://en.wikipedia.org/wiki/Electronic_music', 'https://en.wikipedia.org/wiki/Pop_music', 'https://en.wikipedia.org/wiki/Music', 'https://en.wikipedia.org/wiki/Rock_music']}

In [189]:
non_official_music_channel_handle = "@KoganeMusic"
topic_channel_id = "UCJDvRiWvolEhRLPAVoOzGTA"
non_music_channel_id = "UCiZVMOinTQGb8HQu53VbV4Q"

def get_channel_id_from_handle(handle):
    handle_channel_params = {
        "part": "snippet",
        "forHandle": handle,
        "key": api_key
    }

    handle_channel_response = requests.get(channel_url, params=handle_channel_params)
    handle_channel_data = handle_channel_response.json()

    #print(handle_channel_data)
    snippet = handle_channel_data["items"][0]

    handle_channel_id = snippet["id"]
    #print(handle_channel_id)
    return handle_channel_id

NOM_channel_params = {
    "part": "snippet, topicDetails",
    "id": get_channel_id_from_handle(non_official_music_channel_handle),
    "key": api_key
}

topic_channel_params = {
    "part": "snippet, topicDetails",
    "id": topic_channel_id,
    "key": api_key
}

non_music_channel_params = {
    "part": "snippet, topicDetails",
    "id": non_music_channel_id,
    "key": api_key
}

NOM_channel_response = requests.get(channel_url, params=NOM_channel_params)
topic_channel_response = requests.get(channel_url, params=topic_channel_params)
non_music_channel_response = requests.get(channel_url, params=non_music_channel_params)

channel_data = channel_response.json()
NOM_channel_data = NOM_channel_response.json()
topic_data = topic_channel_response.json()
non_music_data = non_music_channel_response.json()

NOM_channel_item = NOM_channel_data["items"][0]
topic_channel_item = topic_data["items"][0]
non_music_item = non_music_data["items"][0]

Ok now we want to try the same for 3 other items:
A. Official artist
   Set It Off / Ado / YOASOBI

B. Unofficial but definitely music
   one of your cover or lyric channels

C. Definitely non-music
   any normal gaming/commentary channel

In [190]:
print(f"Topic details for Set it Off (Official Music Channel)"
      f"\n {channel_item.get("topicDetails")}")

print(f"Topic details for Kogane Music (Non Official Music Channel)"
      f"\n {NOM_channel_item.get("topicDetails")}")

print(f"Topic details for Lyn (Topic Music Channel)"
      f"\n {topic_channel_item.get("topicDetails")}")

print(f"Topic details for Little Gamer's Playground (Non Music Channel)"
      f"\n {non_music_item.get("topicDetails")}")

Topic details for Set it Off (Official Music Channel)
 {'topicIds': ['/m/064t9', '/m/04rlf', '/m/06by7', '/m/02lkt'], 'topicCategories': ['https://en.wikipedia.org/wiki/Pop_music', 'https://en.wikipedia.org/wiki/Music', 'https://en.wikipedia.org/wiki/Rock_music', 'https://en.wikipedia.org/wiki/Electronic_music']}
Topic details for Kogane Music (Non Official Music Channel)
 {'topicIds': ['/m/028sqc', '/m/04rlf'], 'topicCategories': ['https://en.wikipedia.org/wiki/Music_of_Asia', 'https://en.wikipedia.org/wiki/Music']}
Topic details for Lyn (Topic Music Channel)
 {'topicIds': ['/m/0bzvm2', '/m/028sqc', '/m/04rlf', '/m/064t9'], 'topicCategories': ['https://en.wikipedia.org/wiki/Video_game_culture', 'https://en.wikipedia.org/wiki/Music_of_Asia', 'https://en.wikipedia.org/wiki/Music', 'https://en.wikipedia.org/wiki/Pop_music']}
Topic details for Little Gamer's Playground (Non Music Channel)
 {'topicIds': ['/m/02ntfj', '/m/0bzvm2', '/m/025zzc', '/m/0403l3g'], 'topicCategories': ['https://en.wikipedia.org/wiki/Action-adventure_game', 'https://en.wikipedia.org/wiki/Video_game_culture', 'https://en.wikipedia.org/wiki/Action_game', 'https://en.wikipedia.org/wiki/Role-playing_video_game']}

Interestingly, all 3 music channels contain the same topic ID: "/m/04rlf" which we can assume is the one needed for music, we can use this to classify as channel as a music channel for our filter

### Integrating Music Channel Classification with other classifications

In [193]:
def create_channel_batches(channel_ids):
    channel_ids = list(channel_ids)
    combined_channel_ids_batch = []

    for start_index in range(0, len(channel_ids), BATCH_SIZE):
        channel_ids_batch = channel_ids[start_index:start_index + BATCH_SIZE]
        combined_channel_ids = ",".join(channel_ids_batch)
        combined_channel_ids_batch.append(combined_channel_ids)

    return combined_channel_ids_batch

unique_channel_ids = set()
for candidate in actual_candidates:
    unique_channel_ids.add(candidate.get("channel_id"))

print(f"Number of videos at stage 2, {len(actual_candidates)}")
print(f"Number of unique channel ids, {len(unique_channel_ids)}")

channel_batches = create_channel_batches(unique_channel_ids)

music_channel_ids = set()
unknown_channel_ids = set()
stage_three_filtered_candidates = []

for channel_id_batch in channel_batches:
    channel_params = {
        "part": "snippet,topicDetails",
        "id": channel_id_batch,
        "key": api_key
    }

    channel_response = requests.get(
        channel_url,
        params=channel_params
    )

    channel_data = channel_response.json()

    for channel_item in channel_data["items"]:
        channel_id = channel_item["id"]
        channel_title = channel_item["snippet"]["title"]
        topic_details = channel_item.get("topicDetails")

        if topic_details and "/m/04rlf" in topic_details.get("topicIds", []):
            music_channel_ids.add(channel_id)
            print(f"{channel_title}: music channel")

        else:
            unknown_channel_ids.add(channel_id)
            print(f"{channel_title}: unknown channel")


print("Unique channels:", len(unique_channel_ids))
print("Music channels:", len(music_channel_ids))
print("Unknown channels:", len(unknown_channel_ids))

Number of videos at stage 2, 598
Number of unique channel ids, 177
Official髭男dism: music channel
Shingo Nishimura - Topic: music channel
sxndyalt: music channel
nui: music channel
DanFourts: music channel
Kailash Saire: music channel
InstrUmantal: unknown channel
ImagineDragonsVEVO: music channel
Tokai Teio (CV: Machico) - Topic: music channel
attouです: unknown channel
Kenta Higashiohji - Topic: music channel
青い子 / AOIKO: music channel
Mori Calliope - Topic: music channel
V I P E R (MMD): music channel
しゃみお - Shamisen player Shamio: music channel
Pageless - Topic: music channel
くじらofficial: music channel
tian nya: unknown channel
Release - Topic: unknown channel
Rainych Ran: music channel
Utada Zoey Ch. 歌田ぞおい: unknown channel
WanderingSky114: music channel
Zip: music channel
HIMEHINA Channel: music channel
Wildreamz: unknown channel
MyaMusical: music channel
TAKU INOUE: music channel
Ashvale: music channel
Alekirser Live: unknown channel
🐈Kogane Music: music channel
Talon: unknown channel
Gold Ship (CV: Hitomi Ueda) - Topic: music channel
ヨルシカ / n-buna Official: music channel
ツユ: music channel
tuki.(17): music channel
godwin972: music channel
Shihoko Hirata - Topic: music channel
AkaneMikkyo: music channel
soyuzmusic: music channel
AtariX: unknown channel
Jose Pavli: music channel
imase: music channel
羊羊🐏meimei: music channel
Michael Giacchino - Topic: music channel
Release - Topic: unknown channel
NightcrawlersVEVO: music channel
Marvelous Sunday (CV: Marie Miyake) - Topic: unknown channel
Anniechan_Channel: music channel
Release - Topic: unknown channel
Narita Brian (CV: Rika Kinugawa) - Topic: music channel
Milan Records USA: music channel
Skrillex: music channel
Release - Topic: unknown channel
SFX - Sound Effects For Content Creators: unknown channel
The Bands of HM Royal Marines: music channel
TUYU - Topic: music channel
Tom Cardy: music channel
Rina Tayama - Topic: music channel
Sen: music channel
Equal Vision Records: music channel
With Ether: music channel
L'Orchestra Cinématique: music channel
Suisei Channel: music channel
svthwrd: music channel
Xhomie34: music channel
Nekoha_xD: music channel
Weeaboo Jones: music channel
*namirin: music channel
Shibayan Records: music channel
YOASOBI: music channel
Release - Topic: unknown channel
Aliko Fog: music channel
ビッ栗 skyry13 Acoustic Guitar Channel: music channel
Pageless: music channel
Vanguard Sound Studio: music channel
鳩ピアノ / Pigeon piano: music channel
TikTokPlay: music channel
AKASAKI: music channel
SontheHarry: unknown channel
あかつき るき / Akatsuki Luci: music channel
Tosh Kamura (Official): music channel
O V E R D O S E: unknown channel
Senbei Ch: music channel
Release - Topic: unknown channel
theliftband: music channel
ユウラギ: music channel
龍ヶ崎リン / Rene Ryugasaki【ななしいんく】: music channel
Suisei Channel: music channel
NeroChi: unknown channel
Yxelixi: music channel
Yudha - ユダ: music channel
T.M. Revolution - Topic: music channel
SArisu Chill: music channel
HIKOMARO 一人でバンド: music channel
レヴィ・エリファ-Levi Elipha-: unknown channel
Ado: music channel
kendowater: unknown channel
papa shirogane: music channel
kessoku band - Topic: music channel
FreQuency - Topic: music channel
Minty Reads: music channel
MillerTime: unknown channel
Maylily ASMR: unknown channel
Kazuma Kiryu(Takaya Kuroda) - Topic: music channel
Ein Sof: unknown channel
ARD Klassik: music channel
Pollux: music channel
Jamong: music channel
OAT SAN: music channel
LeeandLie (AmaLee): music channel
Rina Tayama - Topic: music channel
VESPERBELL: music channel
TAK / DORIDORI: music channel
稲葉曇: music channel
fox capture plan - Topic: music channel
RevolverJesusP3: music channel
PSC: music channel
Azumi Takahashi - Topic: music channel
ImagineDragons: music channel
Setsuna「セツナ」: music channel
Jett Pil: music channel
Keizo Ishibashi / 石橋敬三: music channel
Neko4an: music channel
Towa Ch. 常闇トワ: music channel
Arbitraire Turvy: music channel
Higher Ground: music channel
Koyori ch. 博衣こより - holoX -: music channel
mambocore: music channel
Yumi Kawamura - Topic: music channel
Aizawa channel: music channel
bluejob01: music channel
Hiroyuki SAWANO - Topic: music channel
MISIA - Topic: music channel
StrictlyHits: music channel
BUH BUHBUH: music channel
道明寺ここあ / COCOA DOMYOJI: music channel
阿葆: music channel
Release - Topic: unknown channel
Will Stetson: music channel
Matteo Audio: music channel
IRyS - Topic: music channel
Special Week (CV: Azumi Waki) - Topic: music channel
Sound Effects For All: unknown channel
Oliver Udholm: music channel
VESPERBELL_YM: music channel
Nariam1034: music channel
Tedesco Archive: music channel
010鰤: music channel
葉富生 - Topic: music channel
Izuru Ch. 奏手イヅル: music channel
Lizz Robinett: music channel
1 Giờ Chill: music channel
Lyn - Topic: music channel
MachiChunky - Topic: music channel
Midnight Grand Orchestra: music channel
田中: music channel
bloodredshoujo_: music channel
Set It Off - Topic: music channel
JFY GT26: music channel
PROJECT ACES - Topic: music channel
Eleotan: music channel
Release - Topic: unknown channel
THE FIRST TAKE: music channel
gil soundworks: music channel
Masaru Yokoyama - Topic: music channel
月-Tsuki-: music channel
Void: music channel
Sapphire: music channel
Shania Yan: music channel
Crimson: music channel
Kobo Kanaeru Ch. hololive: unknown channel
Free Sound Effects: unknown channel
Keith Power - Topic: music channel
KyuKai: music channel
jen: music channel
rachie 🎀💌: music channel
Set It Off: music channel
Unique channels: 177
Music channels: 148
Unknown channels: 29

## Keyword classification

In [168]:
STRONG_MUSIC_KEYWORDS = [
    "official audio",
    "music video",
    "lyric video",
    "lyrics",
    "cover",
    "remix",
    "instrumental",
    "full song",
    "歌ってみた",
]

WEAK_MUSIC_KEYWORDS = [
    "song",
    "ost",
]

STRONG_NON_MUSIC_KEYWORDS = [
    "sound effect",
    "sfx",
    "asmr",
]

WEAK_NON_MUSIC_KEYWORDS = [
    "reaction",
    "movie clip",
    "tv clip",
    "scene",
    "funny moments",
]

def find_keyword_matches(title, keywords):
    keywords_found = []

    for keyword in keywords:
        if keyword in title.lower():
            keywords_found.append(keyword)

    return keywords_found

def check_candidates_for_keywords(music_candidates):
    for candidate in music_candidates:
        strong_positive_evidence = find_keyword_matches(candidate.get("video_title"), STRONG_MUSIC_KEYWORDS)
        weak_positive_evidence = find_keyword_matches(candidate.get("video_title"), WEAK_MUSIC_KEYWORDS)
        strong_negative_evidence = find_keyword_matches(candidate.get("video_title"), STRONG_NON_MUSIC_KEYWORDS)
        weak_negative_evidence = find_keyword_matches(candidate.get("video_title"), WEAK_NON_MUSIC_KEYWORDS)

        print(f"Strong music keywords in {candidate.get('video_title')}:  {strong_positive_evidence}")
        print(f"Weak music keywords in {candidate.get('video_title')}:  {weak_positive_evidence}")
        print(f"Strong non music keywords in {candidate.get('video_title')}:  {strong_negative_evidence}")
        print(f"weak non music keywords in {candidate.get('video_title')}: {weak_negative_evidence}\n")

check_candidates_for_keywords(actual_candidates)

Strong music keywords in Unknown Mother Goose (wowaka) ♡ English Cover【rachie】アンノウン・マザーグース:  ['cover']
Weak music keywords in Unknown Mother Goose (wowaka) ♡ English Cover【rachie】アンノウン・マザーグース:  []
Strong non music keywords in Unknown Mother Goose (wowaka) ♡ English Cover【rachie】アンノウン・マザーグース:  []
weak non music keywords in Unknown Mother Goose (wowaka) ♡ English Cover【rachie】アンノウン・マザーグース: []

Strong music keywords in Aldnoah.Zero - "aLIEz" (FULL Ending) | ENGLISH ver | AmaLee:  []
Weak music keywords in Aldnoah.Zero - "aLIEz" (FULL Ending) | ENGLISH ver | AmaLee:  []
Strong non music keywords in Aldnoah.Zero - "aLIEz" (FULL Ending) | ENGLISH ver | AmaLee:  []
weak non music keywords in Aldnoah.Zero - "aLIEz" (FULL Ending) | ENGLISH ver | AmaLee: []

Strong music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee:  ['cover']
Weak music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee:  []
Strong non music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee:  []
weak non music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee: []

Strong music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  ['cover']
Weak music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  []
Strong non music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  []
weak non music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover): []

Strong music keywords in monitoring (deco*27) ♥ english cover【rachie】モニタリング:  ['cover']
Weak music keywords in monitoring (deco*27) ♥ english cover【rachie】モニタリング:  []
Strong non music keywords in monitoring (deco*27) ♥ english cover【rachie】モニタリング:  []
weak non music keywords in monitoring (deco*27) ♥ english cover【rachie】モニタリング: []

Strong music keywords in GUM&DROP / 星街すいせい (official):  []
Weak music keywords in GUM&DROP / 星街すいせい (official):  []
Strong non music keywords in GUM&DROP / 星街すいせい (official):  []
weak non music keywords in GUM&DROP / 星街すいせい (official): []

Strong music keywords in The Vampire (DECO*27) ♥ English Cover 【rachie】ヴァンパイア:  ['cover']
Weak music keywords in The Vampire (DECO*27) ♥ English Cover 【rachie】ヴァンパイア:  []
Strong non music keywords in The Vampire (DECO*27) ♥ English Cover 【rachie】ヴァンパイア:  []
weak non music keywords in The Vampire (DECO*27) ♥ English Cover 【rachie】ヴァンパイア: []

Strong music keywords in 稲葉曇『ラグトレイン』Vo. 歌愛ユキ:  []
Weak music keywords in 稲葉曇『ラグトレイン』Vo. 歌愛ユキ:  []
Strong non music keywords in 稲葉曇『ラグトレイン』Vo. 歌愛ユキ:  []
weak non music keywords in 稲葉曇『ラグトレイン』Vo. 歌愛ユキ: []

Strong music keywords in Official髭男dism - Pretender［Official Video］:  []
Weak music keywords in Official髭男dism - Pretender［Official Video］:  []
Strong non music keywords in Official髭男dism - Pretender［Official Video］:  []
weak non music keywords in Official髭男dism - Pretender［Official Video］: []

Strong music keywords in 【Ado】ギラギラ:  []
Weak music keywords in 【Ado】ギラギラ:  []
Strong non music keywords in 【Ado】ギラギラ:  []
weak non music keywords in 【Ado】ギラギラ: []

Strong music keywords in Midnight Grand Orchestra『Moonlightspeed 』Music Video:  ['music video']
Weak music keywords in Midnight Grand Orchestra『Moonlightspeed 』Music Video:  []
Strong non music keywords in Midnight Grand Orchestra『Moonlightspeed 』Music Video:  []
weak non music keywords in Midnight Grand Orchestra『Moonlightspeed 』Music Video: []

Strong music keywords in 「Yona Yona Journey / TAKU INOUE & Mori Calliope」MUSIC VIDEO:  ['music video']
Weak music keywords in 「Yona Yona Journey / TAKU INOUE & Mori Calliope」MUSIC VIDEO:  []
Strong non music keywords in 「Yona Yona Journey / TAKU INOUE & Mori Calliope」MUSIC VIDEO:  []
weak non music keywords in 「Yona Yona Journey / TAKU INOUE & Mori Calliope」MUSIC VIDEO: []

Strong music keywords in Overdose - Kobo Kanaeru (Cover):  ['cover']
Weak music keywords in Overdose - Kobo Kanaeru (Cover):  []
Strong non music keywords in Overdose - Kobo Kanaeru (Cover):  []
weak non music keywords in Overdose - Kobo Kanaeru (Cover): []

Strong music keywords in Why Do I (with Hatsune Miku):  []
Weak music keywords in Why Do I (with Hatsune Miku):  []
Strong non music keywords in Why Do I (with Hatsune Miku):  []
weak non music keywords in Why Do I (with Hatsune Miku): []

Strong music keywords in トレセン音頭 -下剋上 Ver-:  []
Weak music keywords in トレセン音頭 -下剋上 Ver-:  []
Strong non music keywords in トレセン音頭 -下剋上 Ver-:  []
weak non music keywords in トレセン音頭 -下剋上 Ver-: []

Strong music keywords in [Symphonic-Mobile Suite "UC"] 6thMob. :Unicorn Gundam:  []
Weak music keywords in [Symphonic-Mobile Suite "UC"] 6thMob. :Unicorn Gundam:  []
Strong non music keywords in [Symphonic-Mobile Suite "UC"] 6thMob. :Unicorn Gundam:  []
weak non music keywords in [Symphonic-Mobile Suite "UC"] 6thMob. :Unicorn Gundam: []

Strong music keywords in ばかみたい【Taxi Driver Edition】:  []
Weak music keywords in ばかみたい【Taxi Driver Edition】:  []
Strong non music keywords in ばかみたい【Taxi Driver Edition】:  []
weak non music keywords in ばかみたい【Taxi Driver Edition】: []

Strong music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee:  ['cover']
Weak music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee:  []
Strong non music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee:  []
weak non music keywords in "Violet Snow" (Violet Evergarden) 🍓 Cover by Lizz Robinett ft. The Goatee: []

Strong music keywords in 【AKASAKI】Bunny Girl / バニーガール（Lyric Video）:  ['lyric video']
Weak music keywords in 【AKASAKI】Bunny Girl / バニーガール（Lyric Video）:  []
Strong non music keywords in 【AKASAKI】Bunny Girl / バニーガール（Lyric Video）:  []
weak non music keywords in 【AKASAKI】Bunny Girl / バニーガール（Lyric Video）: []

Strong music keywords in No More What Ifs:  []
Weak music keywords in No More What Ifs:  []
Strong non music keywords in No More What Ifs:  []
weak non music keywords in No More What Ifs: []

Strong music keywords in Why Do I (with Hatsune Miku):  []
Weak music keywords in Why Do I (with Hatsune Miku):  []
Strong non music keywords in Why Do I (with Hatsune Miku):  []
weak non music keywords in Why Do I (with Hatsune Miku): []

Strong music keywords in 【Ado】MIRROR:  []
Weak music keywords in 【Ado】MIRROR:  []
Strong non music keywords in 【Ado】MIRROR:  []
weak non music keywords in 【Ado】MIRROR: []

Strong music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video):  ['lyric video']
Weak music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video):  []
Strong non music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video):  []
weak non music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video): []

Strong music keywords in Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble:  []
Weak music keywords in Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble:  []
Strong non music keywords in Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble:  []
weak non music keywords in Driving In My Car (Asgore Runs Over Dess), but Heavenly. Full version + Animation by @xmikamarble: []

Strong music keywords in トレセン音頭:  []
Weak music keywords in トレセン音頭:  []
Strong non music keywords in トレセン音頭:  []
weak non music keywords in トレセン音頭: []

Strong music keywords in BLOW my GALE:  []
Weak music keywords in BLOW my GALE:  []
Strong non music keywords in BLOW my GALE:  []
weak non music keywords in BLOW my GALE: []

Strong music keywords in Ms. VICTORIA:  []
Weak music keywords in Ms. VICTORIA:  []
Strong non music keywords in Ms. VICTORIA:  []
weak non music keywords in Ms. VICTORIA: []

Strong music keywords in マーベラスサンデータイム☆★:  []
Weak music keywords in マーベラスサンデータイム☆★:  []
Strong non music keywords in マーベラスサンデータイム☆★:  []
weak non music keywords in マーベラスサンデータイム☆★: []

Strong music keywords in GIRLS' LEGEND U:  []
Weak music keywords in GIRLS' LEGEND U:  []
Strong non music keywords in GIRLS' LEGEND U:  []
weak non music keywords in GIRLS' LEGEND U: []

Strong music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  ['cover']
Weak music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
Strong non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
weak non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ: []

Strong music keywords in ツユ - それでも雨は降るんだね MV:  []
Weak music keywords in ツユ - それでも雨は降るんだね MV:  []
Strong non music keywords in ツユ - それでも雨は降るんだね MV:  []
weak non music keywords in ツユ - それでも雨は降るんだね MV: []

Strong music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】:  []
Weak music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】:  []
Strong non music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】:  []
weak non music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】: []

Strong music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  ['歌ってみた']
Weak music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  []
Strong non music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  []
weak non music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY: []

Strong music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ):  ['cover']
Weak music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ):  []
Strong non music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ):  []
weak non music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ): []

Strong music keywords in No More What Ifs:  []
Weak music keywords in No More What Ifs:  []
Strong non music keywords in No More What Ifs:  []
weak non music keywords in No More What Ifs: []

Strong music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  ['歌ってみた']
Weak music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  []
Strong non music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  []
weak non music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY: []

Strong music keywords in Why Do I (with Hatsune Miku):  []
Weak music keywords in Why Do I (with Hatsune Miku):  []
Strong non music keywords in Why Do I (with Hatsune Miku):  []
weak non music keywords in Why Do I (with Hatsune Miku): []

Strong music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video):  ['lyric video']
Weak music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video):  []
Strong non music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video):  []
weak non music keywords in Imagine Dragons - Take Me To The Beach (feat. Ado) (Official Lyric Video): []

Strong music keywords in 【Ado】MIRROR:  []
Weak music keywords in 【Ado】MIRROR:  []
Strong non music keywords in 【Ado】MIRROR:  []
weak non music keywords in 【Ado】MIRROR: []

Strong music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE:  []
Weak music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE:  []
Strong non music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE:  []
weak non music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE: []

Strong music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  ['cover']
Weak music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  []
Strong non music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  []
weak non music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover): []

Strong music keywords in 【Ado】オールナイトレディオ:  []
Weak music keywords in 【Ado】オールナイトレディオ:  []
Strong non music keywords in 【Ado】オールナイトレディオ:  []
weak non music keywords in 【Ado】オールナイトレディオ: []

Strong music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】:  []
Weak music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】:  []
Strong non music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】:  []
weak non music keywords in だから僕は音楽を辞めた/ヨルシカ【弾き語りカバー】: []

Strong music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  ['cover']
Weak music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
Strong non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
weak non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ: []

Strong music keywords in STRANGER THAN HEAVEN Theme but the cleanest version:  []
Weak music keywords in STRANGER THAN HEAVEN Theme but the cleanest version:  []
Strong non music keywords in STRANGER THAN HEAVEN Theme but the cleanest version:  []
weak non music keywords in STRANGER THAN HEAVEN Theme but the cleanest version: []

Strong music keywords in Tears of orphans:  []
Weak music keywords in Tears of orphans:  []
Strong non music keywords in Tears of orphans:  []
weak non music keywords in Tears of orphans: []

Strong music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  ['cover']
Weak music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
Strong non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
weak non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ: []

Strong music keywords in 【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき):  ['cover', '歌ってみた']
Weak music keywords in 【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき):  []
Strong non music keywords in 【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき):  []
weak non music keywords in 【歌ってみた】洗脳 / RADWIMPS (Cover by あかつき るき): []

Strong music keywords in 三原色 - YOASOBI (Cover) / VESPERBELL × 松永依織:  ['cover']
Weak music keywords in 三原色 - YOASOBI (Cover) / VESPERBELL × 松永依織:  []
Strong non music keywords in 三原色 - YOASOBI (Cover) / VESPERBELL × 松永依織:  []
weak non music keywords in 三原色 - YOASOBI (Cover) / VESPERBELL × 松永依織: []

Strong music keywords in GIRLS' LEGEND U:  []
Weak music keywords in GIRLS' LEGEND U:  []
Strong non music keywords in GIRLS' LEGEND U:  []
weak non music keywords in GIRLS' LEGEND U: []

Strong music keywords in Umapyoi Celebrity:  []
Weak music keywords in Umapyoi Celebrity:  []
Strong non music keywords in Umapyoi Celebrity:  []
weak non music keywords in Umapyoi Celebrity: []

Strong music keywords in トレセン音頭:  []
Weak music keywords in トレセン音頭:  []
Strong non music keywords in トレセン音頭:  []
weak non music keywords in トレセン音頭: []

Strong music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  ['歌ってみた']
Weak music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  []
Strong non music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY:  []
weak non music keywords in 【歌ってみた】喜劇 カバー 羊羊｜フルVer. #星野源 #SPY_FAMILY: []

Strong music keywords in ツユ - それでも雨は降るんだね MV:  []
Weak music keywords in ツユ - それでも雨は降るんだね MV:  []
Strong non music keywords in ツユ - それでも雨は降るんだね MV:  []
weak non music keywords in ツユ - それでも雨は降るんだね MV: []

Strong music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  ['cover']
Weak music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
Strong non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ:  []
weak non music keywords in 奏  - スキマスイッチ (Cover) / VESPERBELL ヨミ: []

Strong music keywords in Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ]:  ['lyrics']
Weak music keywords in Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ]:  []
Strong non music keywords in Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ]:  []
weak non music keywords in Hana ni Bourei (Yorushika) - Inui Toko x Hoshimachi Suisei [ Lyrics / Nijisanji / Hololive ]: []

Strong music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE:  []
Weak music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE:  []
Strong non music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE:  []
weak non music keywords in 星街すいせい - Stellar Stellar / THE FIRST TAKE: []

Strong music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire:  []
Weak music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire:  []
Strong non music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire:  []
weak non music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire: []

Strong music keywords in Tears of orphans:  []
Weak music keywords in Tears of orphans:  []
Strong non music keywords in Tears of orphans:  []
weak non music keywords in Tears of orphans: []

Strong music keywords in 凱旋門賞 最後の決戦:  []
Weak music keywords in 凱旋門賞 最後の決戦:  []
Strong non music keywords in 凱旋門賞 最後の決戦:  []
weak non music keywords in 凱旋門賞 最後の決戦: []

Strong music keywords in Set It Off - Why Do I:  []
Weak music keywords in Set It Off - Why Do I:  []
Strong non music keywords in Set It Off - Why Do I:  []
weak non music keywords in Set It Off - Why Do I: []

Strong music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  ['cover']
Weak music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  []
Strong non music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover):  []
weak non music keywords in Nightcore / Sped Up → Ai Đưa Em Về (Rock Version/Cover): []

Strong music keywords in 凱旋門賞:  []
Weak music keywords in 凱旋門賞:  []
Strong non music keywords in 凱旋門賞:  []
weak non music keywords in 凱旋門賞: []

Strong music keywords in トレセン音頭 -下剋上 Ver-:  []
Weak music keywords in トレセン音頭 -下剋上 Ver-:  []
Strong non music keywords in トレセン音頭 -下剋上 Ver-:  []
weak non music keywords in トレセン音頭 -下剋上 Ver-: []

Strong music keywords in Umapyoi Celebrity:  []
Weak music keywords in Umapyoi Celebrity:  []
Strong non music keywords in Umapyoi Celebrity:  []
weak non music keywords in Umapyoi Celebrity: []

Strong music keywords in チューリングカレアヤ:  []
Weak music keywords in チューリングカレアヤ:  []
Strong non music keywords in チューリングカレアヤ:  []
weak non music keywords in チューリングカレアヤ: []

Strong music keywords in Alekirser's Sleep Clinic is Open For Business (ASMR):  []
Weak music keywords in Alekirser's Sleep Clinic is Open For Business (ASMR):  []
Strong non music keywords in Alekirser's Sleep Clinic is Open For Business (ASMR):  ['asmr']
weak non music keywords in Alekirser's Sleep Clinic is Open For Business (ASMR): []

Strong music keywords in トレセン音頭:  []
Weak music keywords in トレセン音頭:  []
Strong non music keywords in トレセン音頭:  []
weak non music keywords in トレセン音頭: []

Strong music keywords in GIRLS' LEGEND U:  []
Weak music keywords in GIRLS' LEGEND U:  []
Strong non music keywords in GIRLS' LEGEND U:  []
weak non music keywords in GIRLS' LEGEND U: []

Strong music keywords in 【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】:  ['lyrics']
Weak music keywords in 【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】:  []
Strong non music keywords in 【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】:  []
weak non music keywords in 【ウマ娘】GIRLS' LEGEND U (Game Size)【暫定版】 (パート分け/Color Coded/Lyrics)【ゲーム版ウマ娘メインテーマ】: []

Strong music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ):  ['cover']
Weak music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ):  []
Strong non music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ):  []
weak non music keywords in 白日 / King Gnu (Covered by レヴィ・エリファ): []

Strong music keywords in Why Do I (with Hatsune Miku):  []
Weak music keywords in Why Do I (with Hatsune Miku):  []
Strong non music keywords in Why Do I (with Hatsune Miku):  []
weak non music keywords in Why Do I (with Hatsune Miku): []

Strong music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire:  []
Weak music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire:  []
Strong non music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire:  []
weak non music keywords in Persona 5 Royal ‖  "No More What Ifs" ‖  @TheConsoulsBand  feat. Sapphire: []

Strong music keywords in 【Ado】MIRROR:  []
Weak music keywords in 【Ado】MIRROR:  []
Strong non music keywords in 【Ado】MIRROR:  []

I feel like this is a good way to find "non-official" videos like lyrics or covers, but it i feel like our keywords are being a bit restrictive, maybe instead of using them to flag a video as being music, we use it as the opposite, we use this to define what isn't music